(()=>{'use strict';
if(window.__SDB_I18N__)return;
const LOCALES=['id-ID','en-US','ms-MY','ar-SA','zh-CN','zh-TW','ja-JP','ko-KR','hi-IN','th-TH','vi-VN','fr-FR','de-DE','es-ES','pt-BR','tr-TR','ru-RU','nl-NL'];
const KEYS=['nav.general','nav.public','nav.admin','nav.kds','nav.database','nav.settings','nav.transactions','nav.language','nav.printer','action.openPublic','action.logout','action.back','action.add','action.process','action.ready','action.handover','action.reject','action.refresh','action.close','action.save','menu.all','menu.choose','kds.new','kds.processing','kds.ready','kds.empty','payment.title','payment.qris','payment.download','payment.proof','payment.send','payment.saving','payment.sent','receipt.proofOrder','receipt.transaction','receipt.status','receipt.code','receipt.customer','receipt.service','receipt.table','receipt.orderDate','receipt.orderTime','receipt.method','receipt.paymentTime','receipt.cashier','receipt.items','receipt.subtotal','receipt.total','receipt.received','receipt.change','receipt.thanks','receipt.keep','database.history','database.sync','database.spreadsheet','status.available','status.unavailable','login.title','action.edit','action.addCategory','menu.category','menu.name','menu.price','common.yes','common.no'];
const V={
'id-ID':['GENERAL','SITUS PUBLIK','SITUS ADMIN','KDS','DATABASE','PENGATURAN','Transaksi dan Pembayaran','Bahasa','Printer Thermal','Buka Publik ↗','Keluar','← Kembali','+ Tambah','Proses Pesanan','Tandai Pesanan Siap','Pesanan Diserahkan','Tolak','↻ Perbarui','Tutup','Simpan','Semua','Pilih Menu Favorit Anda','Pesanan Baru','Sedang Diproses','Pesanan Siap','Belum ada pesanan.','Pembayaran Pesanan','Bayar dengan QRIS','Unduh QRIS','Bukti pembayaran','Kirim Pesanan & Konfirmasi','Bukti pembayaran telah diverifikasi. Pesanan sedang disimpan ke sistem…','Pesanan berhasil dikirim','BUKTI PEMBAYARAN & PEMESANAN','STRUK TRANSAKSI','Status Pembayaran','Kode Transaksi','Nama Pemesan','Layanan','Nomor Meja','Tanggal Pemesanan','Waktu Pemesanan','Metode Pembayaran','Waktu Pembayaran','Petugas Kasir','Rincian Pesanan','Subtotal','Total Pembayaran','Nominal Diterima','Kembalian','Terima kasih atas kunjungan Anda.','Simpan struk ini sebagai bukti transaksi.','Riwayat Pesanan','Sinkronisasi','Spreadsheet','Tersedia','Tidak Tersedia','Masuk','Edit','+ Tambah Kategori','Kategori','Nama','Harga','Ya','Tidak'],
'en-US':['GENERAL','PUBLIC SITE','ADMIN SITE','KDS','DATABASE','SETTINGS','Transactions and Payments','Language','Thermal Printer','Open Public ↗','Logout','← Back','+ Add','Process Order','Mark Order Ready','Order Handed Over','Reject','↻ Refresh','Close','Save','All','Choose Your Favorite Menu','New Orders','In Progress','Ready Orders','No orders yet.','Order Payment','Pay with QRIS','Download QRIS','Payment proof','Send Order & Confirm','Payment proof verified. Saving order to the system…','Order sent successfully','PAYMENT & ORDER PROOF','TRANSACTION RECEIPT','Payment Status','Transaction Code','Customer Name','Service','Table Number','Order Date','Order Time','Payment Method','Payment Time','Cashier','Order Details','Subtotal','Total Payment','Amount Received','Change','Thank you for your visit.','Keep this receipt as proof of transaction.','Order History','Synchronization','Spreadsheet','Available','Unavailable','Sign In','Edit','+ Add Category','Category','Name','Price','Yes','No'],
'ms-MY':['UMUM','LAMAN AWAM','LAMAN ADMIN','KDS','PANGKALAN DATA','TETAPAN','Transaksi dan Pembayaran','Bahasa','Pencetak Terma','Buka Awam ↗','Keluar','← Kembali','+ Tambah','Proses Pesanan','Tandakan Pesanan Siap','Pesanan Diserahkan','Tolak','↻ Segar Semula','Tutup','Simpan','Semua','Pilih Menu Kegemaran Anda','Pesanan Baharu','Sedang Diproses','Pesanan Siap','Belum ada pesanan.','Pembayaran Pesanan','Bayar dengan QRIS','Muat Turun QRIS','Bukti pembayaran','Hantar Pesanan & Sahkan','Bukti pembayaran disahkan. Pesanan sedang disimpan…','Pesanan berjaya dihantar','BUKTI PEMBAYARAN & PESANAN','RESIT TRANSAKSI','Status Pembayaran','Kod Transaksi','Nama Pelanggan','Perkhidmatan','Nombor Meja','Tarikh Pesanan','Masa Pesanan','Kaedah Pembayaran','Masa Pembayaran','Juruwang','Butiran Pesanan','Subtotal','Jumlah Bayaran','Jumlah Diterima','Baki','Terima kasih atas kunjungan anda.','Simpan resit ini sebagai bukti transaksi.','Sejarah Pesanan','Penyegerakan','Hamparan','Tersedia','Tidak Tersedia','Log Masuk','Edit','+ Tambah Kategori','Kategori','Nama','Harga','Ya','Tidak'],
'ar-SA':['عام','الموقع العام','موقع الإدارة','KDS','قاعدة البيانات','الإعدادات','المعاملات والمدفوعات','اللغة','الطابعة الحرارية','فتح الموقع العام ↗','تسجيل الخروج','رجوع ←','+ إضافة','معالجة الطلب','تحديد الطلب جاهزًا','تم تسليم الطلب','رفض','↻ تحديث','إغلاق','حفظ','الكل','اختر قائمتك المفضلة','طلبات جديدة','قيد المعالجة','طلبات جاهزة','لا توجد طلبات.','دفع الطلب','الدفع عبر QRIS','تنزيل QRIS','إثبات الدفع','إرسال الطلب والتأكيد','تم التحقق من إثبات الدفع. جارٍ حفظ الطلب…','تم إرسال الطلب بنجاح','إثبات الدفع والطلب','إيصال المعاملة','حالة الدفع','رمز المعاملة','اسم العميل','الخدمة','رقم الطاولة','تاريخ الطلب','وقت الطلب','طريقة الدفع','وقت الدفع','أمين الصندوق','تفاصيل الطلب','المجموع الفرعي','إجمالي الدفع','المبلغ المستلم','الباقي','شكرًا لزيارتكم.','احتفظ بهذا الإيصال كإثبات للمعاملة.','سجل الطلبات','المزامنة','جدول البيانات','متاح','غير متاح','تسجيل الدخول','تعديل','+ إضافة فئة','الفئة','الاسم','السعر','نعم','لا'],
'zh-CN':['常规','公共网站','管理网站','厨房显示','数据库','设置','交易与支付','语言','热敏打印机','打开公共页面 ↗','退出','← 返回','+ 添加','处理订单','标记为已备妥','订单已交付','拒绝','↻ 刷新','关闭','保存','全部','选择您喜欢的菜单','新订单','处理中','已备妥','暂无订单。','订单支付','使用 QRIS 支付','下载 QRIS','付款凭证','发送订单并确认','付款凭证已验证，正在保存订单…','订单发送成功','付款与订单凭证','交易收据','付款状态','交易代码','顾客姓名','服务方式','桌号','下单日期','下单时间','支付方式','付款时间','收银员','订单明细','小计','付款总额','实收金额','找零','感谢您的光临。','请保留此收据作为交易凭证。','订单历史','同步','电子表格','可用','不可用','登录','编辑','+ 添加分类','分类','名称','价格','是','否'],
'zh-TW':['一般','公開網站','管理網站','廚房顯示','資料庫','設定','交易與付款','語言','熱感印表機','開啟公開頁面 ↗','登出','← 返回','+ 新增','處理訂單','標記為已備妥','訂單已交付','拒絕','↻ 重新整理','關閉','儲存','全部','選擇您喜愛的菜單','新訂單','處理中','已備妥','目前沒有訂單。','訂單付款','使用 QRIS 付款','下載 QRIS','付款證明','送出訂單並確認','付款證明已驗證，正在儲存訂單…','訂單已成功送出','付款與訂單證明','交易收據','付款狀態','交易代碼','顧客姓名','服務方式','桌號','訂單日期','訂單時間','付款方式','付款時間','收銀員','訂單明細','小計','付款總額','實收金額','找零','感謝您的光臨。','請保留此收據作為交易證明。','訂單記錄','同步','試算表','可用','不可用','登入','編輯','+ 新增分類','分類','名稱','價格','是','否'],
'ja-JP':['一般','公開サイト','管理サイト','KDS','データベース','設定','取引と支払い','言語','サーマルプリンター','公開画面を開く ↗','ログアウト','← 戻る','+ 追加','注文を処理','注文を準備完了にする','注文を引き渡し済みにする','拒否','↻ 更新','閉じる','保存','すべて','お気に入りのメニューを選択','新規注文','処理中','準備完了','注文はありません。','注文の支払い','QRISで支払う','QRISをダウンロード','支払い証明','注文を送信して確認','支払い証明を確認しました。注文を保存しています…','注文を送信しました','支払い・注文証明','取引レシート','支払い状況','取引コード','顧客名','サービス','テーブル番号','注文日','注文時刻','支払い方法','支払い時刻','レジ担当','注文内容','小計','支払い合計','受取金額','お釣り','ご来店ありがとうございます。','このレシートを取引証明として保管してください。','注文履歴','同期','スプレッドシート','利用可能','利用不可','ログイン','編集','+ カテゴリ追加','カテゴリ','名前','価格','はい','いいえ'],
'ko-KR':['일반','공개 사이트','관리자 사이트','KDS','데이터베이스','설정','거래 및 결제','언어','감열 프린터','공개 화면 열기 ↗','로그아웃','← 뒤로','+ 추가','주문 처리','주문 준비 완료','주문 전달 완료','거절','↻ 새로고침','닫기','저장','전체','좋아하는 메뉴를 선택하세요','새 주문','처리 중','준비 완료','주문이 없습니다.','주문 결제','QRIS로 결제','QRIS 다운로드','결제 증빙','주문 전송 및 확인','결제 증빙이 확인되었습니다. 주문을 저장하는 중…','주문이 전송되었습니다','결제 및 주문 증빙','거래 영수증','결제 상태','거래 코드','고객 이름','서비스','테이블 번호','주문 날짜','주문 시간','결제 방법','결제 시간','계산원','주문 내역','소계','총 결제액','받은 금액','거스름돈','방문해 주셔서 감사합니다.','이 영수증을 거래 증빙으로 보관하세요.','주문 내역','동기화','스프레드시트','사용 가능','사용 불가','로그인','편집','+ 카테고리 추가','카테고리','이름','가격','예','아니요'],
'hi-IN':['सामान्य','सार्वजनिक साइट','एडमिन साइट','KDS','डेटाबेस','सेटिंग्स','लेनदेन और भुगतान','भाषा','थर्मल प्रिंटर','सार्वजनिक पृष्ठ खोलें ↗','लॉग आउट','← वापस','+ जोड़ें','ऑर्डर प्रोसेस करें','ऑर्डर तैयार चिह्नित करें','ऑर्डर सौंपा गया','अस्वीकार','↻ रीफ्रेश','बंद करें','सहेजें','सभी','अपना पसंदीदा मेनू चुनें','नए ऑर्डर','प्रक्रिया में','ऑर्डर तैयार','कोई ऑर्डर नहीं।','ऑर्डर भुगतान','QRIS से भुगतान','QRIS डाउनलोड करें','भुगतान प्रमाण','ऑर्डर भेजें और पुष्टि करें','भुगतान प्रमाण सत्यापित है। ऑर्डर सहेजा जा रहा है…','ऑर्डर सफलतापूर्वक भेजा गया','भुगतान और ऑर्डर प्रमाण','लेनदेन रसीद','भुगतान स्थिति','लेनदेन कोड','ग्राहक का नाम','सेवा','टेबल नंबर','ऑर्डर तारीख','ऑर्डर समय','भुगतान विधि','भुगतान समय','कैशियर','ऑर्डर विवरण','उप-योग','कुल भुगतान','प्राप्त राशि','बाकी','आपकी यात्रा के लिए धन्यवाद।','इस रसीद को लेनदेन प्रमाण के रूप में रखें।','ऑर्डर इतिहास','सिंक्रोनाइज़ेशन','स्प्रेडशीट','उपलब्ध','अनुपलब्ध','लॉग इन','संपादित करें','+ श्रेणी जोड़ें','श्रेणी','नाम','मूल्य','हाँ','नहीं'],
'th-TH':['ทั่วไป','เว็บไซต์สาธารณะ','เว็บไซต์ผู้ดูแล','KDS','ฐานข้อมูล','การตั้งค่า','ธุรกรรมและการชำระเงิน','ภาษา','เครื่องพิมพ์ความร้อน','เปิดหน้าสาธารณะ ↗','ออกจากระบบ','← กลับ','+ เพิ่ม','ดำเนินการคำสั่งซื้อ','ทำเครื่องหมายว่าพร้อม','ส่งมอบคำสั่งซื้อแล้ว','ปฏิเสธ','↻ รีเฟรช','ปิด','บันทึก','ทั้งหมด','เลือกเมนูโปรดของคุณ','คำสั่งซื้อใหม่','กำลังดำเนินการ','พร้อมแล้ว','ยังไม่มีคำสั่งซื้อ','การชำระเงินคำสั่งซื้อ','ชำระด้วย QRIS','ดาวน์โหลด QRIS','หลักฐานการชำระเงิน','ส่งคำสั่งซื้อและยืนยัน','ตรวจสอบหลักฐานการชำระเงินแล้ว กำลังบันทึกคำสั่งซื้อ…','ส่งคำสั่งซื้อสำเร็จ','หลักฐานการชำระเงินและคำสั่งซื้อ','ใบเสร็จธุรกรรม','สถานะการชำระเงิน','รหัสธุรกรรม','ชื่อลูกค้า','บริการ','หมายเลขโต๊ะ','วันที่สั่งซื้อ','เวลาสั่งซื้อ','วิธีชำระเงิน','เวลาชำระเงิน','แคชเชียร์','รายละเอียดคำสั่งซื้อ','ยอดรวมย่อย','ยอดชำระทั้งหมด','จำนวนเงินที่รับ','เงินทอน','ขอบคุณที่มาใช้บริการ','เก็บใบเสร็จนี้ไว้เป็นหลักฐานการทำธุรกรรม','ประวัติคำสั่งซื้อ','การซิงค์','สเปรดชีต','พร้อมใช้งาน','ไม่พร้อมใช้งาน','เข้าสู่ระบบ','แก้ไข','+ เพิ่มหมวดหมู่','หมวดหมู่','ชื่อ','ราคา','ใช่','ไม่'],
'vi-VN':['CHUNG','TRANG CÔNG KHAI','TRANG QUẢN TRỊ','KDS','CƠ SỞ DỮ LIỆU','CÀI ĐẶT','Giao dịch và Thanh toán','Ngôn ngữ','Máy in nhiệt','Mở trang công khai ↗','Đăng xuất','← Quay lại','+ Thêm','Xử lý đơn','Đánh dấu đơn sẵn sàng','Đã giao đơn','Từ chối','↻ Làm mới','Đóng','Lưu','Tất cả','Chọn món yêu thích','Đơn mới','Đang xử lý','Đơn sẵn sàng','Chưa có đơn hàng.','Thanh toán đơn hàng','Thanh toán bằng QRIS','Tải QRIS','Bằng chứng thanh toán','Gửi đơn & Xác nhận','Bằng chứng thanh toán đã được xác minh. Đang lưu đơn…','Đã gửi đơn thành công','BẰNG CHỨNG THANH TOÁN & ĐƠN HÀNG','HÓA ĐƠN GIAO DỊCH','Trạng thái thanh toán','Mã giao dịch','Tên khách hàng','Dịch vụ','Số bàn','Ngày đặt hàng','Giờ đặt hàng','Phương thức thanh toán','Giờ thanh toán','Thu ngân','Chi tiết đơn hàng','Tạm tính','Tổng thanh toán','Số tiền nhận','Tiền thừa','Cảm ơn quý khách.','Hãy giữ hóa đơn này làm bằng chứng giao dịch.','Lịch sử đơn hàng','Đồng bộ','Bảng tính','Có sẵn','Không có sẵn','Đăng nhập','Sửa','+ Thêm danh mục','Danh mục','Tên','Giá','Có','Không'],
'fr-FR':['GÉNÉRAL','SITE PUBLIC','SITE ADMIN','KDS','BASE DE DONNÉES','PARAMÈTRES','Transactions et paiements','Langue','Imprimante thermique','Ouvrir le public ↗','Déconnexion','← Retour','+ Ajouter','Traiter la commande','Marquer prête','Commande remise','Rejeter','↻ Actualiser','Fermer','Enregistrer','Tout','Choisissez votre menu préféré','Nouvelles commandes','En cours','Commandes prêtes','Aucune commande.','Paiement de commande','Payer par QRIS','Télécharger QRIS','Preuve de paiement','Envoyer et confirmer','Preuve de paiement vérifiée. Enregistrement de la commande…','Commande envoyée','PREUVE DE PAIEMENT & COMMANDE','REÇU DE TRANSACTION','Statut du paiement','Code de transaction','Nom du client','Service','Numéro de table','Date de commande','Heure de commande','Mode de paiement','Heure de paiement','Caissier','Détails de la commande','Sous-total','Total payé','Montant reçu','Monnaie','Merci de votre visite.','Conservez ce reçu comme preuve de transaction.','Historique des commandes','Synchronisation','Feuille de calcul','Disponible','Indisponible','Connexion','Modifier','+ Ajouter une catégorie','Catégorie','Nom','Prix','Oui','Non'],
'de-DE':['ALLGEMEIN','ÖFFENTLICHE SEITE','ADMIN-SEITE','KDS','DATENBANK','EINSTELLUNGEN','Transaktionen und Zahlungen','Sprache','Thermodrucker','Öffentliche Seite öffnen ↗','Abmelden','← Zurück','+ Hinzufügen','Bestellung bearbeiten','Als bereit markieren','Bestellung übergeben','Ablehnen','↻ Aktualisieren','Schließen','Speichern','Alle','Wählen Sie Ihr Lieblingsmenü','Neue Bestellungen','In Bearbeitung','Bereite Bestellungen','Noch keine Bestellungen.','Bestellzahlung','Mit QRIS bezahlen','QRIS herunterladen','Zahlungsnachweis','Bestellung senden & bestätigen','Zahlungsnachweis bestätigt. Bestellung wird gespeichert…','Bestellung erfolgreich gesendet','ZAHLUNGS- & BESTELLNACHWEIS','TRANSAKTIONSBELEG','Zahlungsstatus','Transaktionscode','Kundenname','Service','Tischnummer','Bestelldatum','Bestellzeit','Zahlungsmethode','Zahlungszeit','Kassierer','Bestelldetails','Zwischensumme','Gesamtzahlung','Erhaltener Betrag','Rückgeld','Vielen Dank für Ihren Besuch.','Bewahren Sie diesen Beleg als Transaktionsnachweis auf.','Bestellverlauf','Synchronisierung','Tabelle','Verfügbar','Nicht verfügbar','Anmelden','Bearbeiten','+ Kategorie hinzufügen','Kategorie','Name','Preis','Ja','Nein'],
'es-ES':['GENERAL','SITIO PÚBLICO','SITIO ADMIN','KDS','BASE DE DATOS','CONFIGURACIÓN','Transacciones y pagos','Idioma','Impresora térmica','Abrir público ↗','Cerrar sesión','← Volver','+ Añadir','Procesar pedido','Marcar pedido listo','Pedido entregado','Rechazar','↻ Actualizar','Cerrar','Guardar','Todos','Elige tu menú favorito','Pedidos nuevos','En proceso','Pedidos listos','No hay pedidos.','Pago del pedido','Pagar con QRIS','Descargar QRIS','Comprobante de pago','Enviar pedido y confirmar','Comprobante verificado. Guardando pedido…','Pedido enviado correctamente','COMPROBANTE DE PAGO Y PEDIDO','RECIBO DE TRANSACCIÓN','Estado del pago','Código de transacción','Nombre del cliente','Servicio','Número de mesa','Fecha del pedido','Hora del pedido','Método de pago','Hora de pago','Cajero','Detalle del pedido','Subtotal','Pago total','Importe recibido','Cambio','Gracias por su visita.','Conserve este recibo como comprobante de transacción.','Historial de pedidos','Sincronización','Hoja de cálculo','Disponible','No disponible','Iniciar sesión','Editar','+ Añadir categoría','Categoría','Nombre','Precio','Sí','No'],
'pt-BR':['GERAL','SITE PÚBLICO','SITE ADMIN','KDS','BANCO DE DADOS','CONFIGURAÇÕES','Transações e pagamentos','Idioma','Impressora térmica','Abrir público ↗','Sair','← Voltar','+ Adicionar','Processar pedido','Marcar pedido pronto','Pedido entregue','Rejeitar','↻ Atualizar','Fechar','Salvar','Todos','Escolha seu menu favorito','Novos pedidos','Em processamento','Pedidos prontos','Nenhum pedido.','Pagamento do pedido','Pagar com QRIS','Baixar QRIS','Comprovante de pagamento','Enviar pedido e confirmar','Comprovante verificado. Salvando pedido…','Pedido enviado com sucesso','COMPROVANTE DE PAGAMENTO E PEDIDO','RECIBO DA TRANSAÇÃO','Status do pagamento','Código da transação','Nome do cliente','Serviço','Número da mesa','Data do pedido','Hora do pedido','Forma de pagamento','Hora do pagamento','Caixa','Detalhes do pedido','Subtotal','Pagamento total','Valor recebido','Troco','Obrigado pela visita.','Guarde este recibo como comprovante da transação.','Histórico de pedidos','Sincronização','Planilha','Disponível','Indisponível','Entrar','Editar','+ Adicionar categoria','Categoria','Nome','Preço','Sim','Não'],
'tr-TR':['GENEL','HALKA AÇIK SİTE','YÖNETİCİ SİTESİ','KDS','VERİTABANI','AYARLAR','İşlemler ve Ödemeler','Dil','Termal Yazıcı','Halka Açık Sayfayı Aç ↗','Çıkış','← Geri','+ Ekle','Siparişi İşle','Siparişi Hazır Olarak İşaretle','Sipariş Teslim Edildi','Reddet','↻ Yenile','Kapat','Kaydet','Tümü','Favori Menünüzü Seçin','Yeni Siparişler','İşleniyor','Hazır Siparişler','Henüz sipariş yok.','Sipariş Ödemesi','QRIS ile Öde','QRIS İndir','Ödeme kanıtı','Siparişi Gönder ve Onayla','Ödeme kanıtı doğrulandı. Sipariş kaydediliyor…','Sipariş başarıyla gönderildi','ÖDEME VE SİPARİŞ KANITI','İŞLEM FİŞİ','Ödeme Durumu','İşlem Kodu','Müşteri Adı','Hizmet','Masa Numarası','Sipariş Tarihi','Sipariş Saati','Ödeme Yöntemi','Ödeme Saati','Kasiyer','Sipariş Detayları','Ara Toplam','Toplam Ödeme','Alınan Tutar','Para Üstü','Ziyaretiniz için teşekkürler.','Bu fişi işlem kanıtı olarak saklayın.','Sipariş Geçmişi','Senkronizasyon','E-Tablo','Mevcut','Mevcut Değil','Giriş','Düzenle','+ Kategori Ekle','Kategori','Ad','Fiyat','Evet','Hayır'],
'ru-RU':['ОБЩЕЕ','ПУБЛИЧНЫЙ САЙТ','САЙТ АДМИНА','KDS','БАЗА ДАННЫХ','НАСТРОЙКИ','Транзакции и платежи','Язык','Термопринтер','Открыть публичную страницу ↗','Выйти','← Назад','+ Добавить','Обработать заказ','Отметить заказ готовым','Заказ передан','Отклонить','↻ Обновить','Закрыть','Сохранить','Все','Выберите любимое меню','Новые заказы','В обработке','Готовые заказы','Заказов пока нет.','Оплата заказа','Оплатить через QRIS','Скачать QRIS','Подтверждение оплаты','Отправить заказ и подтвердить','Подтверждение оплаты проверено. Заказ сохраняется…','Заказ успешно отправлен','ПОДТВЕРЖДЕНИЕ ОПЛАТЫ И ЗАКАЗА','ЧЕК ТРАНЗАКЦИИ','Статус оплаты','Код транзакции','Имя клиента','Обслуживание','Номер стола','Дата заказа','Время заказа','Способ оплаты','Время оплаты','Кассир','Состав заказа','Подытог','Итого к оплате','Полученная сумма','Сдача','Спасибо за ваш визит.','Сохраните этот чек как подтверждение транзакции.','История заказов','Синхронизация','Таблица','Доступно','Недоступно','Войти','Изменить','+ Добавить категорию','Категория','Имя','Цена','Да','Нет'],
'nl-NL':['ALGEMEEN','PUBLIEKE SITE','ADMIN-SITE','KDS','DATABASE','INSTELLINGEN','Transacties en betalingen','Taal','Thermische printer','Publiek openen ↗','Uitloggen','← Terug','+ Toevoegen','Bestelling verwerken','Als gereed markeren','Bestelling overhandigd','Weigeren','↻ Vernieuwen','Sluiten','Opslaan','Alles','Kies uw favoriete menu','Nieuwe bestellingen','In behandeling','Bestellingen gereed','Nog geen bestellingen.','Bestelling betalen','Betalen met QRIS','QRIS downloaden','Betalingsbewijs','Bestelling verzenden en bevestigen','Betalingsbewijs geverifieerd. Bestelling wordt opgeslagen…','Bestelling succesvol verzonden','BETALINGS- & BESTELBEWIJS','TRANSACTIEBON','Betaalstatus','Transactiecode','Klantnaam','Service','Tafelnummer','Besteldatum','Besteltijd','Betaalmethode','Betaaltijd','Kassier','Bestelgegevens','Subtotaal','Totaalbetaling','Ontvangen bedrag','Wisselgeld','Bedankt voor uw bezoek.','Bewaar deze bon als transactiebewijs.','Bestelgeschiedenis','Synchronisatie','Spreadsheet','Beschikbaar','Niet beschikbaar','Inloggen','Bewerken','+ Categorie toevoegen','Categorie','Naam','Prijs','Ja','Nee']
};
for(const l of LOCALES)if(!Array.isArray(V[l])||V[l].length!==KEYS.length)throw Error('i18n_catalog_incomplete:'+l);
const C=Object.fromEntries(LOCALES.map(l=>[l,Object.fromEntries(KEYS.map((k,i)=>[k,V[l][i]]))]));
const EXTRA_KEYS=['service.dine','service.takeaway','payment.cash','payment.paid'];
const EXTRA_VALUES={
'id-ID':['Makan di Tempat','Bawa Pulang','Tunai','LUNAS'],
'en-US':['Dine In','Take Away','Cash','PAID'],
'ms-MY':['Makan di Tempat','Bawa Pulang','Tunai','DIBAYAR'],
'ar-SA':['تناول في المكان','سفري','نقدًا','مدفوع'],
'zh-CN':['堂食','外带','现金','已付款'],
'zh-TW':['內用','外帶','現金','已付款'],
'ja-JP':['店内','持ち帰り','現金','支払済み'],
'ko-KR':['매장 식사','포장','현금','결제 완료'],
'hi-IN':['यहीं खाएँ','पैक करें','नकद','भुगतान किया गया'],
'th-TH':['รับประทานที่ร้าน','ซื้อกลับ','เงินสด','ชำระแล้ว'],
'vi-VN':['Dùng tại chỗ','Mang đi','Tiền mặt','ĐÃ THANH TOÁN'],
'fr-FR':['Sur place','À emporter','Espèces','PAYÉ'],
'de-DE':['Vor Ort','Zum Mitnehmen','Bar','BEZAHLT'],
'es-ES':['Comer aquí','Para llevar','Efectivo','PAGADO'],
'pt-BR':['No local','Para viagem','Dinheiro','PAGO'],
'tr-TR':['Yerinde','Paket','Nakit','ÖDENDİ'],
'ru-RU':['В заведении','Навынос','Наличные','ОПЛАЧЕНО'],
'nl-NL':['Ter plaatse','Afhalen','Contant','BETAALD']
};
for(const l of LOCALES)for(let i=0;i<EXTRA_KEYS.length;i++)C[l][EXTRA_KEYS[i]]=EXTRA_VALUES[l]?.[i]??EXTRA_VALUES['id-ID'][i];
const ALL_KEYS=[...KEYS,...EXTRA_KEYS];
const reverse=new Map();for(const l of LOCALES)for(const k of ALL_KEYS)reverse.set(String(C[l][k]).trim().toLowerCase(),k);
const source={'GENERAL':'nav.general','SITUS PUBLIK':'nav.public','SITUS ADMIN':'nav.admin','KDS':'nav.kds','DATABASE':'nav.database','PENGATURAN':'nav.settings','Transaksi dan Pembayaran':'nav.transactions','Bahasa':'nav.language','Printer Thermal':'nav.printer','Buka Publik ↗':'action.openPublic','Keluar':'action.logout','← Kembali':'action.back','+ Tambah':'action.add','Proses Pesanan':'action.process','Tandai Pesanan Siap':'action.ready','Pesanan Diserahkan':'action.handover','Tolak':'action.reject','↻ Perbarui':'action.refresh','Tutup':'action.close','Simpan':'action.save','Semua':'menu.all','Pilih Menu Favorit Anda':'menu.choose','Pesanan Baru':'kds.new','Sedang Diproses':'kds.processing','Pesanan Siap':'kds.ready','Belum ada pesanan.':'kds.empty','Pembayaran Pesanan':'payment.title','Bayar dengan QRIS':'payment.qris','Unduh QRIS':'payment.download','Bukti pembayaran':'payment.proof','Kirim Pesanan & Konfirmasi':'payment.send','BUKTI PEMBAYARAN & PEMESANAN':'receipt.proofOrder','STRUK TRANSAKSI':'receipt.transaction','Status Pembayaran':'receipt.status','Kode Transaksi':'receipt.code','Nama Pemesan':'receipt.customer','Layanan':'receipt.service','Nomor Meja':'receipt.table','Tanggal Pemesanan':'receipt.orderDate','Waktu Pemesanan':'receipt.orderTime','Metode Pembayaran':'receipt.method','Waktu Pembayaran':'receipt.paymentTime','Petugas Kasir':'receipt.cashier','Rincian Pesanan':'receipt.items','Subtotal':'receipt.subtotal','Total Pembayaran':'receipt.total','Nominal Diterima':'receipt.received','Kembalian':'receipt.change','Terima kasih atas kunjungan Anda.':'receipt.thanks','Simpan struk ini sebagai bukti transaksi.':'receipt.keep','Riwayat Pesanan':'database.history','Sinkronisasi':'database.sync','Spreadsheet':'database.spreadsheet','Tersedia':'status.available','Tidak Tersedia':'status.unavailable','Masuk':'login.title','Edit':'action.edit','+ Tambah Kategori':'action.addCategory','Kategori':'menu.category','Nama':'menu.name','Harga':'menu.price','Ya':'common.yes','Tidak':'common.no'};
for(const [txt,k] of Object.entries(source))reverse.set(txt.trim().toLowerCase(),k);
const LEGACY={
'id-ID':{
'Lewati ke konten utama':'Lewati ke konten utama','Pilih jenis layanan':'Pilih jenis layanan','DINE IN':'MAKAN DI TEMPAT','TAKE AWAY':'BAWA PULANG','Pilih meja':'Pilih meja','Pastikan nomor meja sesuai meja yang Anda gunakan.':'Pastikan nomor meja sesuai meja yang Anda gunakan.','Lanjut Pilih Menu →':'Lanjut Pilih Menu →','Bagian dari':'Bagian dari','BAGIAN DARI':'BAGIAN DARI','Halaman Beranda':'Halaman Beranda','Halaman Menu':'Halaman Menu','Konfirmasi Menu & Identitas':'Konfirmasi Menu & Identitas','Nomor WhatsApp (opsional)':'Nomor WhatsApp (opsional)','Keterangan':'Keterangan','Lanjut Pembayaran':'Lanjut Pembayaran','AREA PRODUSEN':'AREA PRODUSEN','Login dipisahkan dari layar operasional dapur. Setelah autentikasi berhasil, Kitchen Display System dibuka.':'Login dipisahkan dari layar operasional dapur. Setelah autentikasi berhasil, Kitchen Display System dibuka.','AKSES TERPROTEKSI':'AKSES TERPROTEKSI','Masuk ke KDS':'Masuk ke KDS','Gunakan akun pengelola dan kata sandi.':'Gunakan akun pengelola dan kata sandi.','Email pengelola':'Email pengelola','Kata sandi':'Kata sandi','Masuk ke Kitchen Display System':'Masuk ke Kitchen Display System','LOGIN ADMIN':'LOGIN ADMIN','Masuk ke Studio':'Masuk ke Studio','Email':'Email','Password':'Kata sandi','Pesanan Dapur':'Pesanan Dapur','Smart Cashier':'Smart Cashier','Ketersediaan Barang':'Ketersediaan Barang','Pesanan masuk dan siap ditangani dapur':'Pesanan masuk dan siap ditangani dapur','Pesanan yang sedang dikerjakan dapur':'Pesanan yang sedang dikerjakan dapur','Pesanan siap disajikan atau diserahkan':'Pesanan siap disajikan atau diserahkan','Bukti Pembayaran':'Bukti Pembayaran','Customer Name':'Nama Pemesan','Cetak Struk':'Cetak Struk','BUKTI TRANSAKSI':'BUKTI TRANSAKSI','Struk Transaksi':'Struk Transaksi','Wajib diisi':'Wajib diisi','Bagian /':'Bagian /'},
'en-US':{
'Lewati ke konten utama':'Skip to main content','Pilih jenis layanan':'Choose service type','DINE IN':'DINE IN','TAKE AWAY':'TAKE AWAY','Pilih meja':'Choose a table','Pastikan nomor meja sesuai meja yang Anda gunakan.':'Make sure the table number matches the table you are using.','Lanjut Pilih Menu →':'Continue to Menu →','Bagian dari':'Part of','BAGIAN DARI':'PART OF','Halaman Beranda':'Home Page','Halaman Menu':'Menu Page','Konfirmasi Menu & Identitas':'Confirm Menu & Identity','Nomor WhatsApp (opsional)':'WhatsApp Number (optional)','Keterangan':'Notes','Lanjut Pembayaran':'Continue to Payment','AREA PRODUSEN':'PRODUCER AREA','Login dipisahkan dari layar operasional dapur. Setelah autentikasi berhasil, Kitchen Display System dibuka.':'Login is separated from the kitchen operations screen. After successful authentication, the Kitchen Display System opens.','AKSES TERPROTEKSI':'PROTECTED ACCESS','Masuk ke KDS':'Sign in to KDS','Gunakan akun pengelola dan kata sandi.':'Use your manager account and password.','Email pengelola':'Manager email','Kata sandi':'Password','Masuk ke Kitchen Display System':'Sign in to Kitchen Display System','LOGIN ADMIN':'ADMIN LOGIN','Masuk ke Studio':'Sign in to Studio','Email':'Email','Password':'Password','Pesanan Dapur':'Kitchen Orders','Smart Cashier':'Smart Cashier','Ketersediaan Barang':'Item Availability','Pesanan masuk dan siap ditangani dapur':'Incoming orders ready for the kitchen.','Pesanan yang sedang dikerjakan dapur':'Orders currently being prepared.','Pesanan siap disajikan atau diserahkan':'Orders ready to serve or hand over.','Bukti Pembayaran':'Payment Proof','Customer Name':'Customer Name','Cetak Struk':'Print Receipt','BUKTI TRANSAKSI':'TRANSACTION PROOF','Struk Transaksi':'Transaction Receipt','Wajib diisi':'Required','Bagian /':'Part of /'},
'ar-SA':{
'Lewati ke konten utama':'انتقل إلى المحتوى الرئيسي','Pilih jenis layanan':'اختر نوع الخدمة','DINE IN':'تناول في المكان','TAKE AWAY':'طلب خارجي','Pilih meja':'اختر الطاولة','Pastikan nomor meja sesuai meja yang Anda gunakan.':'تأكد من أن رقم الطاولة يطابق الطاولة التي تستخدمها.','Lanjut Pilih Menu →':'متابعة إلى القائمة ←','Bagian dari':'جزء من','BAGIAN DARI':'جزء من','Halaman Beranda':'الصفحة الرئيسية','Halaman Menu':'صفحة القائمة','Konfirmasi Menu & Identitas':'تأكيد القائمة والهوية','Nomor WhatsApp (opsional)':'رقم واتساب (اختياري)','Keterangan':'ملاحظات','Lanjut Pembayaran':'متابعة الدفع','AREA PRODUSEN':'منطقة الإنتاج','Login dipisahkan dari layar operasional dapur. Setelah autentikasi berhasil, Kitchen Display System dibuka.':'تسجيل الدخول منفصل عن شاشة تشغيل المطبخ. بعد نجاح المصادقة يتم فتح نظام عرض المطبخ.','AKSES TERPROTEKSI':'وصول محمي','Masuk ke KDS':'تسجيل الدخول إلى KDS','Gunakan akun pengelola dan kata sandi.':'استخدم حساب المدير وكلمة المرور.','Email pengelola':'بريد المدير الإلكتروني','Kata sandi':'كلمة المرور','Masuk ke Kitchen Display System':'تسجيل الدخول إلى نظام عرض المطبخ','LOGIN ADMIN':'تسجيل دخول الإدارة','Masuk ke Studio':'تسجيل الدخول إلى الاستوديو','Email':'البريد الإلكتروني','Password':'كلمة المرور','Pesanan Dapur':'طلبات المطبخ','Smart Cashier':'الكاشير الذكي','Ketersediaan Barang':'توفر الأصناف','Pesanan masuk dan siap ditangani dapur':'طلبات واردة جاهزة للمطبخ.','Pesanan yang sedang dikerjakan dapur':'طلبات قيد التحضير في المطبخ.','Pesanan siap disajikan atau diserahkan':'طلبات جاهزة للتقديم أو التسليم.','Bukti Pembayaran':'إثبات الدفع','Customer Name':'اسم العميل','Cetak Struk':'طباعة الإيصال','BUKTI TRANSAKSI':'إثبات المعاملة','Struk Transaksi':'إيصال المعاملة','Wajib diisi':'مطلوب','Bagian /':'جزء من /'}
};
const legacyReverse=new Map();for(const [loc,map] of Object.entries(LEGACY))for(const [src,val] of Object.entries(map)){legacyReverse.set(src.trim().toLowerCase(),src);legacyReverse.set(String(val).trim().toLowerCase(),src)}
function legacyText(s){const raw=String(s||'').trim(),src=legacyReverse.get(raw.toLowerCase());if(src)return LEGACY[current]?.[src]??LEGACY['id-ID'][src]??raw;const m=raw.match(/^(?:MEJA|Meja|Table(?: Number)?|الطاولة)\s+(\d+)$/i);if(m)return t('receipt.table')+' '+m[1];return''}
function canonical(v){v=String(v||'').trim();if(LOCALES.includes(v))return v;const p=v.toLowerCase().split('-')[0],x=LOCALES.find(l=>l.toLowerCase().split('-')[0]===p);return x||'id-ID'}
let current=canonical(document.documentElement.dataset.adminLanguage||document.documentElement.dataset.sdbLanguage||window.__SDB_TENANT_CONFIG?.locale||document.documentElement.lang||'id-ID');
const t=k=>C[current]?.[k]||C['id-ID'][k]||k;
const SUB_KEYS={'Bahasa':'nav.language','Transaksi dan Pembayaran':'nav.transactions','Printer Thermal':'nav.printer','Riwayat Pesanan':'database.history','Sinkronisasi':'database.sync','Spreadsheet':'database.spreadsheet'};
function routeKey(el){const d=el?.dataset;if(!d)return'';if(d.main==='general')return'nav.general';if(d.main==='public')return'nav.public';if(d.main==='admin')return'nav.admin';if(d.main==='kds')return'nav.kds';if(d.main==='database')return'nav.database';if(d.settingsMain!==undefined||d.settingsMainV29!==undefined||d.settingsMainV2!==undefined)return'nav.settings';if(d.act==='start'||d.act==='verify_start')return'action.process';if(d.act==='ready')return'action.ready';if(d.act==='complete')return'action.handover';if(d.act==='reject_payment')return'action.reject';return''}
const textKey=s=>reverse.get(String(s||'').trim().toLowerCase())||'';
let resolveCache=new Map();
function resolvedText(s){const raw=String(s||'').trim();if(!raw)return'';const ck=current+'\u0000'+raw;if(resolveCache.has(ck))return resolveCache.get(ck);const k=textKey(raw),v=k?t(k):legacyText(raw);resolveCache.set(ck,v||'');return v||''}
function setNodeText(node,next){if(node.nodeValue===next)return false;node.nodeValue=next;return true}
function setElementText(el,next){if(el.textContent===next)return false;el.textContent=next;return true}
function setAttr(el,name,next){if(el.getAttribute(name)===next)return false;el.setAttribute(name,next);return true}
function translateNode(node){if(!node)return false;let changed=false;if(node.nodeType===3){const parent=node.parentElement;if(!parent||/^(SCRIPT|STYLE|CODE|PRE|TEXTAREA)$/i.test(parent.tagName))return false;const raw=String(node.nodeValue||''),trim=raw.trim();if(!trim)return false;const next=resolvedText(trim);if(next){const lead=raw.match(/^\s*/)?.[0]||'',tail=raw.match(/\s*$/)?.[0]||'';changed=setNodeText(node,lead+next+tail)||changed}return changed}if(node.nodeType!==1)return false;const el=node,d=el.dataset||{},explicit=d.i18n||routeKey(el);if(explicit)changed=setElementText(el,t(explicit))||changed;for(const a of ['placeholder','title','aria-label']){const v=el.getAttribute?.(a);if(!v)continue;const next=resolvedText(v);if(next)changed=setAttr(el,a,next)||changed}const raw=String(d.sub||d.settingsSub||d.settingsSubV29||d.settingsSubV2||'');if(raw&&SUB_KEYS[raw])changed=setElementText(el,t(SUB_KEYS[raw]))||changed;return changed}
function syncMeta(){const root=document.documentElement,lang=current.split('-')[0],dir=current==='ar-SA'?'rtl':'ltr';if(root.dataset.sdbLanguage!==current)root.dataset.sdbLanguage=current;if(root.lang!==lang)root.lang=lang;if(root.dir!==dir)root.dir=dir}
function translateSubtree(root=document,emit=false){if(!root)return false;let changed=translateNode(root);if(root.nodeType===1||root.nodeType===9||root.nodeType===11){const w=document.createTreeWalker(root,NodeFilter.SHOW_ELEMENT|NodeFilter.SHOW_TEXT);let n;while((n=w.nextNode()))changed=translateNode(n)||changed}syncMeta();if(emit)document.dispatchEvent(new CustomEvent('sdb:i18n-applied',{detail:{locale:current}}));return changed}
function translate(root=document){return translateSubtree(root,true)}
function setLocale(v){const next=canonical(v);if(next===current){syncMeta();return current}current=next;resolveCache=new Map();translate(document);return current}
const locale=()=>current;
let queued=false;const pendingRoots=new Set();
function queueRoot(root){if(!root)return;pendingRoots.add(root);if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;const roots=[...pendingRoots];pendingRoots.clear();const minimal=roots.filter((r,i)=>!roots.some((p,j)=>i!==j&&p?.nodeType===1&&r!==p&&p.contains?.(r)));let changed=false;for(const root of minimal){if(root===document||root?.isConnected)changed=translateSubtree(root,false)||changed}if(changed)document.dispatchEvent(new CustomEvent('sdb:i18n-applied',{detail:{locale:current}}))})}
function dynamicRoot(){return document.getElementById('view')||document.getElementById('app')||document.getElementById('root')||document.body}
const obs=new MutationObserver(rs=>{for(const r of rs)for(const n of r.addedNodes||[])if(n.nodeType===1||n.nodeType===3)queueRoot(n)});
async function hydrateLocale(){try{const r=await fetch('/api/locale',{cache:'no-store',credentials:'same-origin'});if(r.ok){const x=canonical(await r.text());if(x!==current)setLocale(x);else syncMeta()}}catch{}}
function boot(){translate(document);obs.observe(document.documentElement,{childList:true,subtree:true});hydrateLocale()}
document.addEventListener('sdb:tenant-config',e=>setLocale(e.detail?.locale));
document.addEventListener('rohmat:language-updated',e=>setLocale(e.detail?.code||e.detail?.default||e.detail));
document.addEventListener('rohmat:navigation',()=>queueRoot(dynamicRoot()));
document.addEventListener('rohmat:dom-updated',()=>queueRoot(dynamicRoot()));
const missing=()=>ALL_KEYS.filter(k=>!C[current]?.[k]&&!C['id-ID']?.[k]);window.__SDB_I18N__={locales:[...LOCALES],keys:[...ALL_KEYS],catalog:C,t,setLocale,locale,translate,missing};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();