-- Sanitized DR-only replay snapshot from production migration history.
-- Version: 20260909110127  Name: central_design_system_v2
-- Production-specific credentials, operator identities, and project endpoint were neutralized.

alter table public.site_settings add column if not exists design_system jsonb not null default '{}'::jsonb;

create table if not exists public.design_system_versions (
  id bigint generated by default as identity primary key,
  kind text not null check (kind in ('baseline','draft','published','rollback')),
  theme_id text not null default '',
  theme_name text not null default '',
  payload jsonb not null,
  created_by text,
  restored_from bigint references public.design_system_versions(id) on delete set null,
  created_at timestamptz not null default now()
);

alter table public.design_system_versions enable row level security;
revoke all on public.design_system_versions from anon, authenticated;

create or replace function private.jsonb_deep_merge(a jsonb, b jsonb)
returns jsonb
language sql
immutable
set search_path=''
as $$
  select case
    when jsonb_typeof(coalesce(a,'{}'::jsonb))='object' and jsonb_typeof(coalesce(b,'{}'::jsonb))='object' then
      coalesce((
        select jsonb_object_agg(k,
          case
            when av is not null and bv is not null and jsonb_typeof(av)='object' and jsonb_typeof(bv)='object'
              then private.jsonb_deep_merge(av,bv)
            else coalesce(bv,av)
          end)
        from (
          select coalesce(ak,bk) k, av, bv
          from (select key ak, value av from jsonb_each(coalesce(a,'{}'::jsonb))) aa
          full join (select key bk, value bv from jsonb_each(coalesce(b,'{}'::jsonb))) bb on aa.ak=bb.bk
        ) x
      ),'{}'::jsonb)
    else coalesce(b,a)
  end
$$;

create or replace function private.design_system_apply_payload(p_email text, p_payload jsonb, p_kind text, p_restored_from bigint default null)
returns jsonb
language plpgsql
security definer
set search_path=''
as $$
declare
  v_id bigint;
  v_theme jsonb;
  v_general jsonb;
  v_colors jsonb;
  v_typo jsonb;
  v_layout jsonb;
  v_state jsonb;
  v_existing jsonb;
  v_admin jsonb;
  v_kds jsonb;
  v_old_typo jsonb;
  v_theme_id text;
  v_theme_name text;
begin
  if p_payload is null or jsonb_typeof(p_payload) <> 'object' then
    return jsonb_build_object('ok',false,'error','invalid_payload');
  end if;
  v_theme := coalesce(p_payload->'theme','{}'::jsonb);
  v_general := coalesce(p_payload->'general','{}'::jsonb);
  v_colors := private.jsonb_deep_merge(coalesce(v_theme->'colors','{}'::jsonb),coalesce(v_general->'colors','{}'::jsonb));
  v_typo := private.jsonb_deep_merge(coalesce(v_theme->'typography','{}'::jsonb),coalesce(v_general->'typography','{}'::jsonb));
  v_layout := private.jsonb_deep_merge(coalesce(v_theme->'layout','{}'::jsonb),coalesce(v_general->'layout','{}'::jsonb));
  v_theme_id := left(coalesce(v_theme->>'id',p_payload->>'themeId','custom'),100);
  v_theme_name := left(coalesce(v_theme->>'name',p_payload->>'themeName','Custom Theme'),160);

  insert into public.design_system_versions(kind,theme_id,theme_name,payload,created_by,restored_from)
  values(p_kind,v_theme_id,v_theme_name,p_payload,p_email,p_restored_from)
  returning id into v_id;

  select design_system, admin_design, kds_design, typography
    into v_existing,v_admin,v_kds,v_old_typo
  from public.site_settings where id=1 for update;

  v_state := jsonb_build_object(
    'version',2,
    'published',p_payload || jsonb_build_object('status','published','publishedAt',now(),'publishedBy',p_email),
    'draft',null,
    'publishedVersionId',v_id,
    'updatedAt',now()
  );

  update public.site_settings s set
    design_system=v_state,
    theme_preset='custom',
    color_outer=case when (v_colors->>'background') ~ '^#[0-9A-Fa-f]{6}$' then v_colors->>'background' else s.color_outer end,
    color_panel=case when (v_colors->>'panel') ~ '^#[0-9A-Fa-f]{6}$' then v_colors->>'panel' else s.color_panel end,
    color_primary=case when (v_colors->>'primary') ~ '^#[0-9A-Fa-f]{6}$' then v_colors->>'primary' else s.color_primary end,
    color_accent=case when (v_colors->>'accent') ~ '^#[0-9A-Fa-f]{6}$' then v_colors->>'accent' else s.color_accent end,
    color_text=case when (v_colors->>'text') ~ '^#[0-9A-Fa-f]{6}$' then v_colors->>'text' else s.color_text end,
    color_muted=case when (v_colors->>'muted') ~ '^#[0-9A-Fa-f]{6}$' then v_colors->>'muted' else s.color_muted end,
    content_width=case when coalesce(v_layout->>'width','') in ('compact','balanced','wide') then v_layout->>'width' else s.content_width end,
    typography=private.jsonb_deep_merge(coalesce(v_old_typo,'{}'::jsonb),jsonb_build_object('_general',v_typo)),
    admin_design=private.jsonb_deep_merge(coalesce(v_admin,'{}'::jsonb),jsonb_build_object('_system',jsonb_build_object('version',2,'activeTheme',v_theme_id,'publishedVersionId',v_id,'published',p_payload,'general',v_general))),
    kds_design=private.jsonb_deep_merge(coalesce(v_kds,'{}'::jsonb),jsonb_build_object('_system',jsonb_build_object('version',2,'activeTheme',v_theme_id,'publishedVersionId',v_id,'published',p_payload,'general',v_general))),
    updated_at=now(), updated_by=null
  where s.id=1;

  return jsonb_build_object('ok',true,'versionId',v_id,'designSystem',v_state);
end
$$;

create or replace function public.admin_design_system_save_draft(p_token text, p_payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path=''
as $$
declare
  v_email extensions.citext;
  v_id bigint;
  v_theme jsonb;
  v_state jsonb;
begin
  v_email := private.admin_email_from_token(p_token);
  if v_email is null then return jsonb_build_object('ok',false,'error','invalid_session'); end if;
  if p_payload is null or jsonb_typeof(p_payload)<>'object' then return jsonb_build_object('ok',false,'error','invalid_payload'); end if;
  v_theme:=coalesce(p_payload->'theme','{}'::jsonb);
  insert into public.design_system_versions(kind,theme_id,theme_name,payload,created_by)
  values('draft',left(coalesce(v_theme->>'id','custom'),100),left(coalesce(v_theme->>'name','Custom Theme'),160),p_payload,v_email::text)
  returning id into v_id;
  select design_system into v_state from public.site_settings where id=1 for update;
  v_state:=coalesce(v_state,'{}'::jsonb) || jsonb_build_object('version',2,'draft',p_payload || jsonb_build_object('status','draft','draftVersionId',v_id,'updatedAt',now()),'updatedAt',now());
  update public.site_settings set design_system=v_state,updated_at=now() where id=1;
  return jsonb_build_object('ok',true,'versionId',v_id,'designSystem',v_state);
end
$$;

create or replace function public.admin_design_system_publish(p_token text, p_payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path=''
as $$
declare v_email extensions.citext;
begin
  v_email:=private.admin_email_from_token(p_token);
  if v_email is null then return jsonb_build_object('ok',false,'error','invalid_session'); end if;
  return private.design_system_apply_payload(v_email::text,p_payload,'published',null);
end
$$;

create or replace function public.admin_design_system_rollback(p_token text, p_version_id bigint)
returns jsonb
language plpgsql
security definer
set search_path=''
as $$
declare
  v_email extensions.citext;
  v_payload jsonb;
begin
  v_email:=private.admin_email_from_token(p_token);
  if v_email is null then return jsonb_build_object('ok',false,'error','invalid_session'); end if;
  select payload into v_payload from public.design_system_versions where id=p_version_id and kind in ('baseline','published','rollback');
  if v_payload is null then return jsonb_build_object('ok',false,'error','version_not_found'); end if;
  return private.design_system_apply_payload(v_email::text,v_payload,'rollback',p_version_id);
end
$$;

create or replace function public.admin_design_system_history(p_token text)
returns jsonb
language plpgsql
security definer
set search_path=''
as $$
declare v_email extensions.citext; v_rows jsonb;
begin
  v_email:=private.admin_email_from_token(p_token);
  if v_email is null then return jsonb_build_object('ok',false,'error','invalid_session'); end if;
  select coalesce(jsonb_agg(jsonb_build_object('id',id,'kind',kind,'themeId',theme_id,'themeName',theme_name,'createdAt',created_at,'createdBy',created_by,'restoredFrom',restored_from) order by id desc),'[]'::jsonb)
  into v_rows from (select * from public.design_system_versions order by id desc limit 50) h;
  return jsonb_build_object('ok',true,'versions',v_rows);
end
$$;

create or replace function public.design_system_resolve(p_site text, p_page text default null, p_element text default null)
returns jsonb
language plpgsql
security definer
set search_path=''
as $$
declare
  v_state jsonb; v_pub jsonb; v_eff jsonb;
begin
  select design_system into v_state from public.site_settings where id=1;
  v_pub:=coalesce(v_state->'published','{}'::jsonb);
  v_eff:=coalesce(v_pub->'theme','{}'::jsonb);
  v_eff:=private.jsonb_deep_merge(v_eff,coalesce(v_pub->'general','{}'::jsonb));
  if p_site is not null then v_eff:=private.jsonb_deep_merge(v_eff,coalesce(v_pub#>(array['sites',p_site]),'{}'::jsonb)); end if;
  if p_site is not null and p_page is not null then v_eff:=private.jsonb_deep_merge(v_eff,coalesce(v_pub#>(array['pages',p_site,p_page]),'{}'::jsonb)); end if;
  if p_site is not null and p_page is not null and p_element is not null then v_eff:=private.jsonb_deep_merge(v_eff,coalesce(v_pub#>(array['elements',p_site,p_page,p_element]),'{}'::jsonb)); end if;
  return v_eff;
end
$$;

revoke all on function public.admin_design_system_save_draft(text,jsonb) from public, anon, authenticated;
revoke all on function public.admin_design_system_publish(text,jsonb) from public, anon, authenticated;
revoke all on function public.admin_design_system_rollback(text,bigint) from public, anon, authenticated;
revoke all on function public.admin_design_system_history(text) from public, anon, authenticated;
revoke all on function public.design_system_resolve(text,text,text) from public, anon, authenticated;
grant execute on function public.admin_design_system_save_draft(text,jsonb) to anon, authenticated;
grant execute on function public.admin_design_system_publish(text,jsonb) to anon, authenticated;
grant execute on function public.admin_design_system_rollback(text,bigint) to anon, authenticated;
grant execute on function public.admin_design_system_history(text) to anon, authenticated;

do $$
declare
  s public.site_settings%rowtype;
  v_payload jsonb;
  v_id bigint;
begin
  select * into s from public.site_settings where id=1 for update;
  if s.design_system='{}'::jsonb then
    v_payload:=jsonb_build_object(
      'schemaVersion',2,
      'theme',jsonb_build_object(
        'id','legacy-current','name','Current Production','tag','Migrated safely from current live design',
        'colors',jsonb_build_object('background',s.color_outer,'panel',s.color_panel,'primary',s.color_primary,'accent',s.color_accent,'text',s.color_text,'muted',s.color_muted),
        'typography',jsonb_build_object('family','system-ui','size',15),
        'layout',jsonb_build_object('width',s.content_width,'density','Balanced','radius',22,'shadow','soft','motion','subtle')
      ),
      'general',jsonb_build_object(),
      'sites',jsonb_build_object(),
      'pages',jsonb_build_object(),
      'elements',jsonb_build_object(),
      'meta',jsonb_build_object('migratedFrom','legacy','createdAt',now())
    );
    insert into public.design_system_versions(kind,theme_id,theme_name,payload,created_by)
    values('baseline','legacy-current','Current Production',v_payload,'system-migration') returning id into v_id;
    update public.site_settings set design_system=jsonb_build_object('version',2,'published',v_payload || jsonb_build_object('status','published','publishedAt',now(),'publishedBy','system-migration'),'draft',null,'publishedVersionId',v_id,'updatedAt',now()) where id=1;
  end if;
end $$;
