(()=>{'use strict';
if(window.__rohmatKdsDesignRuntimeV1)return;window.__rohmatKdsDesignRuntimeV1=1;
const FONTS=new Set(['system-ui','Inter','Manrope','Segoe UI','Arial','Helvetica','Calibri','Georgia','Times New Roman','Garamond','Palatino Linotype','Courier New']);
let row=null,sig='',busy=false,timer=0,lastFetch=0;
const MIN_REFRESH_MS=60000,BACKGROUND_REFRESH_MS=300000;
const obj=v=>v&&typeof v==='object'&&!Array.isArray(v)?v:{};
const merge=(a,b)=>{const out={...obj(a)};for(const[k,v]of Object.entries(obj(b)))out[k]=v&&typeof v==='object'&&!Array.isArray(v)?merge(out[k],v):v;return out};
const num=(v,a,b,d)=>{v=Number(v);return Number.isFinite(v)?Math.max(a,Math.min(b,v)):d};
const color=(v,d)=>/^#[0-9a-f]{6}$/i.test(String(v||''))?String(v):d;
function page(){if(document.body?.classList.contains('loginPage'))return'login';const t=document.querySelector('.tab.on')?.dataset.tab;return t==='cashier'?'cashier':t==='stock'?'stock':'orders'}
function resolved(){const p=obj(row?.design_system?.published);let c=merge({},p.theme);c=merge(c,p.general);c=merge(c,obj(p.sites?.kds));c=merge(c,obj(p.pages?.kds?.[page()]));return c}
function apply(){if(!row)return;const c=resolved(),co=obj(c.colors),fallback=obj(row.typography?._general),ty=merge(fallback,obj(c.typography)),ra=obj(c.radius),la=obj(c.layout),root=document.documentElement;let family=String(ty.family||'system-ui');if(!FONTS.has(family))family='system-ui';let head=String(ty.headingFamily||family);if(obj(row?.design_system?.published?.general).typography?.family)head=family;if(!FONTS.has(head))head=family;const size=num(ty.size,5,72,14),lh=num(ty.lineHeight,1,2,1.45),cardR=num(la.radius??ra.card,0,40,18),buttonR=num(ra.button,0,40,12),inputR=num(ra.input,0,40,14);const vars={'--kds-bg':color(co.background,'#0f130f'),'--kds-panel':color(co.panel,'#171c16'),'--kds-primary':color(co.primary,'#215a46'),'--kds-accent':color(co.accent,'#53d3a1'),'--kds-text':color(co.text,'#f6f4ef'),'--kds-muted':color(co.muted,'#969d94'),'--kds-font':JSON.stringify(family)+',system-ui,-apple-system,"Segoe UI",sans-serif','--kds-head-font':JSON.stringify(head)+',system-ui,-apple-system,"Segoe UI",sans-serif','--kds-size':size+'px','--kds-line-height':String(lh),'--kds-card-r':cardR+'px','--kds-btn-r':buttonR+'px','--kds-input-r':inputR+'px'};for(const[k,v]of Object.entries(vars))root.style.setProperty(k,v);const meta=document.querySelector('meta[name="theme-color"]');if(meta)meta.content=vars['--kds-bg'];root.dataset.rohmatKdsDesign='v1';root.dataset.rohmatKdsDesignPage=page()}
async function refresh(force=false){if(busy||(!force&&Date.now()-lastFetch<MIN_REFRESH_MS))return;busy=true;try{await window.__SDB_TENANT_CONFIG_READY;const cfg=window.__SDB_TENANT_CONFIG||{},U=String(cfg.supabaseUrl||''),K=String(cfg.publishableKey||'');if(!U||!K)return;const r=await fetch(U+'/rest/v1/site_settings_kds_design_v1?select=updated_at,typography,design_system&id=eq.1&limit=1',{headers:{apikey:K},cache:'no-store'});lastFetch=Date.now();if(!r.ok)return;const n=(await r.json())?.[0]||{},next=JSON.stringify([n.updated_at,n.design_system?.publishedVersionId]);if(force||next!==sig){row=n;sig=next}apply()}catch{}finally{busy=false}}
function arm(){clearTimeout(timer);if(document.hidden)return;timer=setTimeout(async()=>{await refresh(false);arm()},BACKGROUND_REFRESH_MS)}
window.__rohmatKdsDesignApply=apply;window.__rohmatKdsDesignRefresh=refresh;
document.addEventListener('rohmat:kds-page',apply);window.addEventListener('focus',()=>refresh(false));window.addEventListener('pageshow',()=>refresh(false));document.addEventListener('visibilitychange',()=>{if(document.hidden)clearTimeout(timer);else{refresh(false);arm()}});
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{refresh(true);arm()},{once:true});else{refresh(true);arm()}
})();