import "jsr:@supabase/functions-js/edge-runtime.d.ts";
const CANONICAL="https://rohmat-kds-printer.vercel.app";
const BASE="/functions/v1/rohmat-kds-live-v3";
const MARKER="/rohmat-kds-live-v3";
const Q2=String.raw`(()=>{'use strict';
const stockLocks=new Map();
function cartMap(root){const map=new Map();root.querySelectorAll('.cashLine').forEach(line=>{const minus=line.querySelector('[data-cash-minus]');const qty=Number(line.querySelector('.cashQty b')?.textContent||0);const id=String(minus?.dataset.cashMinus||'');if(id&&qty>0)map.set(id,qty)});return map}
function buildStep(item,id,q){let add=item.querySelector('[data-cash-add]'),step=item.querySelector('.q2step');if(add)add.hidden=true;if(!step){step=document.createElement('div');step.className='q2step cashQty';step.dataset.q2Id=id;step.innerHTML='<button type="button" class="cashBtn primary" data-q2-plus="'+id+'" aria-label="Tambah">+</button><b class="q2qty" aria-live="polite"></b><button type="button" class="cashBtn" data-q2-minus="'+id+'" aria-label="Kurangi">−</button>';item.appendChild(step)}const n=step.querySelector('.q2qty');if(n)n.textContent=String(Math.max(0,q));return step}
function syncStock(){const now=Date.now();for(const [id,l] of [...stockLocks]){if(now>l.until){stockLocks.delete(id);continue}const b=document.querySelector('[data-stock="'+CSS.escape(id)+'"]');if(!b)continue;b.textContent=l.desired?'Tersedia':'Habis';b.dataset.next=l.desired?'0':'1';b.classList.toggle('off',!l.desired);b.closest('.stock')?.classList.toggle('off',!l.desired)}}
function sync(){const root=document.getElementById('cashierRoot');if(root){const qty=cartMap(root);root.querySelectorAll('.cashItem').forEach(item=>{const add=item.querySelector('[data-cash-add]');const existing=item.querySelector('.q2step');const id=String(add?.dataset.cashAdd||existing?.dataset.q2Id||'');if(!id)return;const q=Number(qty.get(id)||0);if(q>0)buildStep(item,id,q);else{if(add)add.hidden=false;if(existing)existing.remove()}})}syncStock()}
let queued=false;function schedule(){if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;sync()})}
document.addEventListener('click',e=>{const nativeAdd=e.target.closest('#cashierRoot [data-cash-add]');if(nativeAdd){const item=nativeAdd.closest('.cashItem'),id=String(nativeAdd.dataset.cashAdd||'');if(item&&id)buildStep(item,id,1);return}const plus=e.target.closest('[data-q2-plus]'),minus=e.target.closest('[data-q2-minus]');if(plus||minus){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();const id=String((plus||minus).dataset[plus?'q2Plus':'q2Minus']||''),step=(plus||minus).closest('.q2step'),qEl=step?.querySelector('.q2qty'),cur=Number(qEl?.textContent||0),next=Math.max(0,cur+(plus?1:-1));if(next>0){if(qEl)qEl.textContent=String(next)}else{const item=step?.closest('.cashItem'),add=item?.querySelector('[data-cash-add]');if(add)add.hidden=false;step?.remove()}const root=document.getElementById('cashierRoot'),target=root?.querySelector((plus?'[data-cash-plus="':'[data-cash-minus="')+CSS.escape(id)+'"]');if(target)target.click();queueMicrotask(schedule);return}const stock=e.target.closest('[data-stock]');if(stock){const id=String(stock.dataset.stock||''),desired=stock.dataset.next==='1';if(id){stockLocks.set(id,{desired,until:Date.now()+5000});stock.textContent=desired?'Tersedia':'Habis';stock.dataset.next=desired?'0':'1';stock.classList.toggle('off',!desired);stock.closest('.stock')?.classList.toggle('off',!desired);schedule()}}},true);
new MutationObserver(schedule).observe(document.documentElement,{childList:true,subtree:true});document.addEventListener('DOMContentLoaded',schedule,{once:true});window.addEventListener('pageshow',schedule);setInterval(syncStock,250);setTimeout(schedule,0);
})();`;
function subpath(u:URL){const i=u.pathname.indexOf(MARKER);if(i<0)return"/";return u.pathname.slice(i+MARKER.length)||"/"}
function rewriteHtml(s:string){return s.replaceAll('src="/','src="'+BASE+'/').replaceAll('href="/','href="'+BASE+'/').replaceAll("src='/","src='"+BASE+"/").replaceAll("href='/","href='"+BASE+"/")}
function rewriteJs(s:string){return s.replaceAll("fetch('/api/kds'","fetch('"+BASE+"/api/kds'").replaceAll('fetch("/api/kds"','fetch("'+BASE+'/api/kds"').replaceAll("location.replace('/login')","location.replace('"+BASE+"/login')").replaceAll('location.replace("/login")','location.replace("'+BASE+'/login")').replaceAll("location.replace('/')","location.replace('"+BASE+"/')").replaceAll('location.replace("/")','location.replace("'+BASE+'/")')}
function headers(type:string){return{"content-type":type,"cache-control":"no-store, max-age=0, must-revalidate","pragma":"no-cache","x-content-type-options":"nosniff","referrer-policy":"no-referrer","permissions-policy":"camera=(), microphone=(), geolocation=(), payment=()","x-rohmat-kds":"supabase-reverse-proxy-native-qty-row-v5"}}
function sanitizeCookie(v:string){return v.replace(/;\s*Domain=[^;]+/ig,'')}
Deno.serve(async(req:Request)=>{const u=new URL(req.url),p=subpath(u);if(req.method==="OPTIONS")return new Response(null,{status:204,headers:{...headers("text/plain"),"access-control-allow-origin":"*","access-control-allow-methods":"GET,HEAD,POST,OPTIONS","access-control-allow-headers":"content-type"}});if(p==="/quantity2.js"||p.startsWith("/quantity2.js?"))return new Response(req.method==="HEAD"?null:Q2,{status:200,headers:headers("application/javascript; charset=utf-8")});if(p==="/api/kds"){if(!["POST","GET","HEAD"].includes(req.method))return new Response("Method Not Allowed",{status:405,headers:headers("text/plain")});const h=new Headers();const ct=req.headers.get("content-type");if(ct)h.set("content-type",ct);const ck=req.headers.get("cookie");if(ck)h.set("cookie",ck);const body=(req.method==="POST")?await req.arrayBuffer():undefined;const r=await fetch(CANONICAL+"/api/kds",{method:req.method,headers:h,body,redirect:"manual",cache:"no-store"});const outH=headers(r.headers.get("content-type")||"application/json; charset=utf-8");const sc=r.headers.get("set-cookie");if(sc)outH["set-cookie"]=sanitizeCookie(sc);const loc=r.headers.get("location");if(loc)outH["location"]=loc.startsWith(CANONICAL)?BASE+new URL(loc).pathname:loc;return new Response(req.method==="HEAD"?null:await r.arrayBuffer(),{status:r.status,headers:outH})}if(!["GET","HEAD"].includes(req.method))return new Response("Method Not Allowed",{status:405,headers:headers("text/plain")});const target=CANONICAL+(p==="/"?"/":p);const r=await fetch(target+u.search,{method:req.method,redirect:"manual",cache:"no-store"});let type=r.headers.get("content-type")||"application/octet-stream";const outH=headers(type);const loc=r.headers.get("location");if(loc){const lu=new URL(loc,CANONICAL);outH["location"]=BASE+lu.pathname+lu.search;return new Response(null,{status:r.status,headers:outH})}if(req.method==="HEAD")return new Response(null,{status:r.status,headers:outH});if(type.includes("text/html")){const t=rewriteHtml(await r.text());return new Response(t,{status:r.status,headers:outH})}if(type.includes("javascript")&&(p==="/app.js"||p==="/login.js"||p.startsWith("/app.js?")||p.startsWith("/login.js?"))){const t=rewriteJs(await r.text());return new Response(t,{status:r.status,headers:outH})}return new Response(await r.arrayBuffer(),{status:r.status,headers:outH})});