(function(){'use strict';
var THEMES={
'Emerald Executive':['Profesional • Hangat • Premium',['#F3F1EC','#FFFFFF','#264B3E','#C86D4D','#22342D']],
'Midnight Pro':['Modern • Kontras • Teknologi',['#0D1320','#151D2C','#5B8CFF','#2DD4BF','#EAF0F7']],
'Graphite Elite':['Netral • Korporat • Elegan',['#ECEEEF','#FFFFFF','#343A3D','#A78155','#23282B']],
'Terracotta Modern':['Hangat • Artisan • Humanis',['#FAF1EA','#FFFDFC','#A94F32','#2F6E61','#3A261D']],
'Oceanic Blue':['Bersih • Segar • Terpercaya',['#EEF5F8','#FFFFFF','#17648A','#F08A4B','#173543']],
'Royal Indigo':['Premium • Formal • Eksklusif',['#F2F1FA','#FFFFFF','#443C91','#D0A33C','#272343']],
'Nordic Light':['Minimal • Terang • Tenang',['#F6F8F9','#FFFFFF','#4E6878','#7FA887','#29353C']],
'Obsidian Gold':['Mewah • Dramatis • Eksklusif',['#0F0F0E','#191816','#C7A23A','#E9E2D0','#F2EEE4']],
'Forest Luxe':['Natural • Premium • Earthy',['#EFF2EC','#FFFFFF','#315942','#BA8659','#1F3328']],
'Slate Professional':['Rapi • Serius • Operasional',['#F2F4F7','#FFFFFF','#41566E','#3D8E9A','#233040']],
'Cyber Mint':['Futuristik • Enerjik • Digital',['#0E1717','#142222','#42E8B4','#8B7CFF','#E4FAF4']],
'Aurora Purple':['Kreatif • Modern • Ekspresif',['#F4F0FA','#FFFFFF','#7048A8','#3CA7A0','#30243E']],
'Solar Orange':['Aktif • Ramah • Mudah terlihat',['#F7F3EE','#FFFFFF','#3C454A','#F08A24','#342B24']],
'Ruby Modern':['Hangat • Berani • Premium',['#F8F1F3','#FFFFFF','#87364D','#C98556','#3A242B']],
'Coffee House':['Klasik • Hangat • Nyaman',['#F5F0E8','#FFFDF9','#6E4D39','#B8794D','#3B2B21']],
'Arctic Glass':['Ringan • Bersih • Kontemporer',['#EDF6FA','#FFFFFF','#3F7896','#6A8FE8','#203745']],
'Neo Teal':['Segar • Modern • Seimbang',['#EAF4F2','#FFFFFF','#19776E','#D48A4A','#183835']],
'Minimal Mono':['Sederhana • Cepat • Utilitarian',['#F6F6F6','#FFFFFF','#202020','#666666','#171717']],
'Future Lime':['Eksperimental • Bold • Futuristik',['#111511','#181D18','#A4E84B','#47B7C6','#EDF4E8']],
'Rose Quartz':['Lembut • Premium • Feminin',['#FBF3F4','#FFFFFF','#A85C70','#B48758','#3C2C31']]};
var FONT_GROUPS={'Sans Modern':['Inter','Plus Jakarta Sans','Manrope','DM Sans','Urbanist','Outfit','Work Sans','Nunito Sans','Rubik','Lato'],'Geometric & Tech':['Poppins','Space Grotesk','Sora','Montserrat','Exo 2','Rajdhani','Oxanium'],'Humanist & UI':['Source Sans 3','IBM Plex Sans','Noto Sans','Open Sans'],'Serif & Editorial':['Playfair Display','Merriweather','Lora','Cormorant Garamond','Libre Baskerville','DM Serif Display','Noto Serif'],'Display & Character':['Bebas Neue','Oswald','Archivo Black','Anton'],'Monospace':['JetBrains Mono','IBM Plex Mono','Roboto Mono','Space Mono'],'System':['System UI','Georgia','Arial','Verdana','Trebuchet MS']};
var bypass=new WeakSet();
function openStudio(name){var old=document.querySelector('.sc-ts-overlay');if(old)old.remove();var ov=document.createElement('div');ov.className='sc-ts-overlay';ov.innerHTML='<div class="sc-ts-framewrap"><button class="sc-ts-close">Tutup</button><iframe class="sc-ts-frame" src="/theme-studio/index.html?embed=1&theme='+encodeURIComponent(name||'')+'"></iframe></div>';document.body.appendChild(ov);ov.querySelector('.sc-ts-close').onclick=function(){ov.remove()};ov.onclick=function(e){if(e.target===ov)ov.remove()};}
function cardName(card){var s=card&&card.querySelector('strong');return s?s.textContent.trim():'';}
document.addEventListener('click',function(e){var card=e.target.closest&&e.target.closest('.theme-card');if(!card||location.pathname!='/kasir/general')return;if(bypass.has(card)){bypass.delete(card);return;}e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();openStudio(cardName(card));},true);
window.addEventListener('message',function(e){var d=e.data||{};if(d.type!=='SC_THEME_APPLY'||!d.theme)return;var card=Array.from(document.querySelectorAll('.theme-card')).find(function(c){return cardName(c)===d.theme});if(card){bypass.add(card);card.click();setTimeout(function(){var ov=document.querySelector('.sc-ts-overlay');if(ov)ov.remove();enhance();},150);}});
function findTypography(){return Array.from(document.querySelectorAll('section.panel')).find(function(s){var h=s.querySelector('h2');return h&&h.textContent.indexOf('Preferensi Tampilan')>=0;});}
function loadFont(f){if(/^(System UI|Georgia|Arial|Verdana|Trebuchet MS)$/.test(f))return;var id='scf-'+f.replace(/[^a-z0-9]/gi,'-').toLowerCase();if(document.getElementById(id))return;var l=document.createElement('link');l.id=id;l.rel='stylesheet';l.href='https://fonts.googleapis.com/css2?family='+encodeURIComponent(f).replace(/%20/g,'+')+':wght@400;500;600;700;800&display=swap';document.head.appendChild(l);}
function styleFonts(h,b){loadFont(h);loadFont(b);var st=document.getElementById('sc-ts-fontstyle');if(!st){st=document.createElement('style');st.id='sc-ts-fontstyle';document.head.appendChild(st);}st.textContent='body{font-family:"'+b+'",system-ui,sans-serif!important} h1,h2,h3,.brand strong,.topbar h1,.kds-brand h1{font-family:"'+h+'",system-ui,sans-serif!important}';}
function options(sel,current){sel.innerHTML='';Object.keys(FONT_GROUPS).forEach(function(g){var og=document.createElement('optgroup');og.label=g;FONT_GROUPS[g].forEach(function(f){var o=document.createElement('option');o.value=f;o.textContent=f;if(f===current)o.selected=true;og.appendChild(o)});sel.appendChild(og)});}
function enhanceTypography(){var sec=findTypography();if(!sec)return;var fields=Array.from(sec.querySelectorAll('.field'));var hf=fields.find(function(f){var s=f.querySelector(':scope > span');return s&&s.textContent.trim()==='Font Heading'}),bf=fields.find(function(f){var s=f.querySelector(':scope > span');return s&&s.textContent.trim()==='Font Body'});if(!hf||!bf)return;var hs=hf.querySelector('select'),bs=bf.querySelector('select');if(!hs||!bs)return;if(hs.dataset.scExpanded!=='1'){options(hs,hs.value);options(bs,bs.value);hs.dataset.scExpanded=bs.dataset.scExpanded='1';}
var prev=sec.querySelector('.sc-ts-font-preview');if(!prev){prev=document.createElement('div');prev.className='sc-ts-font-preview';prev.innerHTML='<div><span class="eyebrow">PREVIEW HEADING</span><strong></strong><small></small></div><div><span class="eyebrow">PREVIEW BODY</span><p>Transaksi, menu, pembayaran, riwayat, dan Kitchen Display System dalam satu alur kerja.</p><small></small></div>';var grid=sec.querySelector('.form-grid');if(grid)grid.before(prev);}
function sync(){var h=hs.value,b=bs.value;styleFonts(h,b);if(prev){prev.querySelector('strong').textContent='SMART CASHIER — Cepat, Rapi, Profesional';prev.querySelector('strong').style.fontFamily='"'+h+'",sans-serif';prev.querySelectorAll('small')[0].textContent=h;prev.querySelector('p').style.fontFamily='"'+b+'",sans-serif';prev.querySelectorAll('small')[1].textContent=b;}}
if(!hs.dataset.scBound){hs.addEventListener('change',sync);bs.addEventListener('change',sync);hs.dataset.scBound=bs.dataset.scBound='1';}sync();}
function enhanceCards(){var grid=document.querySelector('.theme-grid');if(!grid)return;var sec=grid.closest('section.panel');if(sec&&!sec.querySelector('.sc-ts-banner')){var b=document.createElement('div');b.className='sc-ts-banner';b.innerHTML='<span><b>Theme Studio:</b> klik tema untuk Preview → Evaluasi → Terapkan</span><b>20 tema • tidak langsung aktif</b>';grid.before(b);}grid.querySelectorAll('.theme-card').forEach(function(c){if(c.classList.contains('sc-ts-card'))return;c.classList.add('sc-ts-card');var n=cardName(c),d=THEMES[n];if(!d)return;var small=c.querySelector('small');if(small)small.textContent=c.classList.contains('selected')?'Aktif • klik untuk preview':'Preview & evaluasi';var m=document.createElement('div');m.className='sc-ts-meta';m.innerHTML='<span>'+d[0]+'</span><div class="sc-ts-foot"><div class="sc-ts-dots">'+d[1].map(function(x){return '<i style="background:'+x+'"></i>'}).join('')+'</div><b class="sc-ts-ready">'+(c.classList.contains('selected')?'AKTIF':'SIAP')+'</b></div>';c.appendChild(m);});}
function enhance(){if(location.pathname==='/kasir/general'){enhanceCards();enhanceTypography();}}
new MutationObserver(enhance).observe(document.documentElement,{subtree:true,childList:true});setInterval(enhance,900);enhance();
})();