import "jsr:@supabase/functions-js/edge-runtime.d.ts";
const U=Deno.env.get("SUPABASE_URL")||"";
const K=Deno.env.get("SUPABASE_PUBLISHABLE_KEY")||Deno.env.get("SUPABASE_ANON_KEY")||"";
const SNAP='public:admin-style-runtime-v47-captured';
const SHELL_GUARD=`(()=>{'use strict';if(window.__rohmatTenantShellGuardV57)return;window.__rohmatTenantShellGuardV57=1;let s=document.getElementById('rohmatTenantShellGuardV57');if(!s){s=document.createElement('style');s.id='rohmatTenantShellGuardV57';s.textContent='html body .sidebar{background:var(--primary,#315343)!important;color:var(--panel,#FFFDF8)!important;border-right-color:color-mix(in srgb,var(--accent,#B87444) 48%,transparent)!important}html body .sidebar .logoMark{background:var(--accent,#B87444)!important;color:var(--primary,#315343)!important}html body .sidebar .logo b,html body .sidebar .mainNav button.on{color:var(--panel,#FFFDF8)!important}html body .sidebar .logo small,html body .sidebar .sidebarFoot small,html body .sidebar .mainNav button{color:color-mix(in srgb,var(--panel,#FFFDF8) 78%,transparent)!important}html body .sidebar .mainNav button:hover{background:color-mix(in srgb,var(--panel,#FFFDF8) 10%,transparent)!important;color:var(--panel,#FFFDF8)!important}html body .sidebar .mainNav button.on{background:color-mix(in srgb,var(--panel,#FFFDF8) 16%,transparent)!important;box-shadow:inset 3px 0 var(--accent,#B87444)!important}';document.head.appendChild(s)}})();\n`;
const NAV_DEDUPE=`(()=>{'use strict';if(window.__rohmatAdminNavDedupeV56)return;window.__rohmatAdminNavDedupeV56=1;let queued=false;function run(){queued=false;const nav=document.querySelector('.mainNav');if(!nav)return;const xs=[...nav.querySelectorAll('button')].filter(b=>String(b.textContent||'').trim().toUpperCase()==='PENGATURAN');xs.slice(1).forEach(b=>b.remove())}function schedule(){if(queued)return;queued=true;requestAnimationFrame(run)}document.addEventListener('rohmat:navigation',schedule);window.addEventListener('pageshow',schedule);const root=document.getElementById('root');if(root)new MutationObserver(schedule).observe(root,{childList:true,subtree:false});schedule();})();\n`;
const PRELUDE=`(()=>{'use strict';if(!window.__rohmatAdminStaticCssV1){window.__rohmatAdminStaticCssV1={append(id,css){if(document.getElementById(id))return;let s=document.getElementById('rohmatAdminStaticCssV1');if(!s){s=document.createElement('style');s.id='rohmatAdminStaticCssV1';document.head.appendChild(s)}s.appendChild(document.createTextNode('\\n/* '+id+' */\\n'+String(css||'')));const m=document.createElement('meta');m.id=id;m.dataset.rohmatCssConsolidated='v1';document.head.appendChild(m)}}}})();\n`;
let memo:Promise<string>|null=null;
function foldOne(src:string,id:string){const safe=id.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');const re=new RegExp("const s=document\\.createElement\\('style'\\);s\\.id='"+safe+"';s\\.textContent=([\\s\\S]*?);document\\.head\\.appendChild\\(s\\)");let hit=0;const out=src.replace(re,(_m,expr)=>{hit++;return "window.__rohmatAdminStaticCssV1.append('"+id+"',"+expr+");"});return {out,hit}}
function consolidate(src:string){let out=src,total=0;for(const id of ['rohmatEditorCompleteCssV74','rohmatAdminUiFixV47','rohmatAdminUxCssV48']){const r=foldOne(out,id);out=r.out;total+=r.hit}if(total!==3)return src;out=out.replace(/\(\(\)=>\{'use strict';\s*if\(window\.__rohmatAdminGlobalDesignV49\)[\s\S]*?\}\)\(\);\s*/,'');out=out.replace(/add\('rohmat-admin-cashier-safe-v7','https:\/\/[^']+\/functions\/v1\/rohmat-admin-cashier-loader-v1\?v=7'\);/,'').replace('rohmat-admin-database-ui-v1?v=10',"rohmat-admin-database-ui-v1?tenant='+encodeURIComponent(window.__SDB_TENANT_ID__||'')+'&v=19").replace('rohmat-admin-kds-ui-v1?v=6',"rohmat-admin-kds-ui-v1?tenant='+encodeURIComponent(window.__SDB_TENANT_ID__||'')+'&v=12").replace("setInterval(()=>{if(!document.hidden)load(false)},5000)","setInterval(()=>{if(!document.hidden)load(false)},15000)");return PRELUDE+out+SHELL_GUARD+NAV_DEDUPE+'\n;document.documentElement.dataset.rohmatAdminCssConsolidated="v2";';}
async function js(){if(!U||!K)throw new Error('tenant_config_missing');if(memo)return memo;memo=(async()=>{const r=await fetch(U+'/rest/v1/runtime_asset_backups?select=content&name=eq.'+encodeURIComponent(SNAP)+'&limit=1',{headers:{apikey:K,Authorization:'Bearer '+K},cache:'no-store'});if(!r.ok)throw new Error('snapshot_fetch_'+r.status);const a=await r.json(),c=a?.[0]?.content;if(typeof c!=='string'||c.length<40000||!c.includes('__rohmatSafeAddonsV47')||!c.includes('__rohmatAdminUXV48'))throw new Error('snapshot_invalid');return consolidate(c)})();return memo}
Deno.serve(async(req:Request)=>{if(req.method!=='GET'&&req.method!=='HEAD')return new Response('Method Not Allowed',{status:405,headers:{'cache-control':'no-store'}});try{const body=await js();return new Response(req.method==='HEAD'?null:body,{status:200,headers:{'content-type':'application/javascript; charset=utf-8','cache-control':'public, max-age=300, s-maxage=1800, stale-while-revalidate=3600','access-control-allow-origin':'*','cross-origin-resource-policy':'cross-origin','x-content-type-options':'nosniff','etag':'"rohmat-admin-style-runtime-v59-v57"','x-rohmat-admin-style-runtime':'baseline-v47-tenant-theme-single-source-v57'}})}catch(e){return new Response('/* admin runtime baseline unavailable */',{status:503,headers:{'content-type':'application/javascript; charset=utf-8','cache-control':'no-store','x-rohmat-admin-style-error':String((e as Error)?.message||e).slice(0,100)}})}});