import "jsr:@supabase/functions-js/edge-runtime.d.ts";
const U=Deno.env.get("SUPABASE_URL")||"";
const K=Deno.env.get("SUPABASE_PUBLISHABLE_KEY")||Deno.env.get("SUPABASE_ANON_KEY")||"";
const SNAP='public:admin-style-runtime-v47-captured';
const PRELUDE=`(()=>{'use strict';if(!window.__rohmatAdminStaticCssV1){window.__rohmatAdminStaticCssV1={append(id,css){if(document.getElementById(id))return;let s=document.getElementById('rohmatAdminStaticCssV1');if(!s){s=document.createElement('style');s.id='rohmatAdminStaticCssV1';document.head.appendChild(s)}s.appendChild(document.createTextNode('\\n/* '+id+' */\\n'+String(css||'')));const m=document.createElement('meta');m.id=id;m.dataset.rohmatCssConsolidated='v1';document.head.appendChild(m)}}}})();\n`;
let memo:Promise<string>|null=null;
function foldOne(src:string,id:string){const safe=id.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');const re=new RegExp("const s=document\\.createElement\\('style'\\);s\\.id='"+safe+"';s\\.textContent=([\\s\\S]*?);document\\.head\\.appendChild\\(s\\)");let hit=0;const out=src.replace(re,(_m,expr)=>{hit++;return "window.__rohmatAdminStaticCssV1.append('"+id+"',"+expr+");"});return {out,hit}}
function consolidate(src:string){let out=src,total=0;for(const id of ['rohmatEditorCompleteCssV74','rohmatAdminUiFixV47','rohmatAdminUxCssV48']){const r=foldOne(out,id);out=r.out;total+=r.hit}if(total!==3)return src;out=out.replace(/add\('rohmat-admin-cashier-safe-v7','https:\/\/[^']+\/functions\/v1\/rohmat-admin-cashier-loader-v1\?v=7'\);/,'').replace('rohmat-admin-database-ui-v1?v=10',"rohmat-admin-database-ui-v1?tenant='+encodeURIComponent(window.__SDB_TENANT_ID__||'')+'&v=19").replace('rohmat-admin-kds-ui-v1?v=6',"rohmat-admin-kds-ui-v1?tenant='+encodeURIComponent(window.__SDB_TENANT_ID__||'')+'&v=12").replace("setInterval(()=>{if(!document.hidden)load(false)},5000)","setInterval(()=>{if(!document.hidden)load(false)},15000)");return PRELUDE+out+'\n;document.documentElement.dataset.rohmatAdminCssConsolidated="v2";';}
async function js(){if(!U||!K)throw new Error('tenant_config_missing');if(memo)return memo;memo=(async()=>{const r=await fetch(U+'/rest/v1/runtime_asset_backups?select=content&name=eq.'+encodeURIComponent(SNAP)+'&limit=1',{headers:{apikey:K,Authorization:'Bearer '+K},cache:'no-store'});if(!r.ok)throw new Error('snapshot_fetch_'+r.status);const a=await r.json(),c=a?.[0]?.content;if(typeof c!=='string'||c.length<40000||!c.includes('__rohmatSafeAddonsV47')||!c.includes('__rohmatAdminUXV48'))throw new Error('snapshot_invalid');return consolidate(c)})();return memo}
Deno.serve(async(req:Request)=>{if(req.method!=='GET'&&req.method!=='HEAD')return new Response('Method Not Allowed',{status:405,headers:{'cache-control':'no-store'}});try{const body=await js();return new Response(req.method==='HEAD'?null:body,{status:200,headers:{'content-type':'application/javascript; charset=utf-8','cache-control':'public, max-age=300, s-maxage=1800, stale-while-revalidate=3600','access-control-allow-origin':'*','cross-origin-resource-policy':'cross-origin','x-content-type-options':'nosniff','etag':'"rohmat-admin-style-runtime-v59-v54"','x-rohmat-admin-style-runtime':'baseline-1835-v47-css-consolidated-v1'}})}catch(e){return new Response('/* admin runtime baseline unavailable */',{status:503,headers:{'content-type':'application/javascript; charset=utf-8','cache-control':'no-store','x-rohmat-admin-style-error':String((e as Error)?.message||e).slice(0,100)}})}});