-- ROHMAT MASTER PROTOTIPE v1
-- Phase 10: fail-closed tenant resolution by canonical/alias origin for shared Vercel runtimes.

create table if not exists private.tenant_origin_aliases (
  id bigint generated by default as identity primary key,
  tenant_id uuid not null references private.platform_tenants(id) on delete cascade,
  app_kind text not null check(app_kind in ('public','admin','kds')),
  origin text not null,
  enabled boolean not null default true,
  alias_kind text not null default 'custom' check(alias_kind in ('canonical','custom','preview')),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(origin)
);
alter table private.tenant_origin_aliases enable row level security;
revoke all on private.tenant_origin_aliases from anon,authenticated;
drop policy if exists tenant_origin_aliases_service_role_all on private.tenant_origin_aliases;
create policy tenant_origin_aliases_service_role_all
on private.tenant_origin_aliases for all to service_role using(true) with check(true);
drop trigger if exists trg_tenant_origin_aliases_updated_at on private.tenant_origin_aliases;
create trigger trg_tenant_origin_aliases_updated_at
before update on private.tenant_origin_aliases
for each row execute function public.set_updated_at();

create or replace function private.normalize_https_origin(p_origin text)
returns text
language plpgsql
immutable
set search_path=''
as $$
declare v text;
begin
  v:=lower(trim(coalesce(p_origin,'')));
  if v='' then return null; end if;
  v:=regexp_replace(v,'/+$','');
  if v !~ '^https://[a-z0-9.-]+(:[0-9]{1,5})?$' then return null; end if;
  return v;
end
$$;

insert into private.tenant_origin_aliases(tenant_id,app_kind,origin,alias_kind,metadata)
select tenant_id,'public',private.normalize_https_origin(public_origin),'canonical','{}'::jsonb
from private.tenant_runtime_config where enabled and private.normalize_https_origin(public_origin) is not null
on conflict(origin) do update set tenant_id=excluded.tenant_id,app_kind=excluded.app_kind,enabled=true,alias_kind='canonical',updated_at=now();

insert into private.tenant_origin_aliases(tenant_id,app_kind,origin,alias_kind,metadata)
select tenant_id,'admin',private.normalize_https_origin(admin_origin),'canonical','{}'::jsonb
from private.tenant_runtime_config where enabled and private.normalize_https_origin(admin_origin) is not null
on conflict(origin) do update set tenant_id=excluded.tenant_id,app_kind=excluded.app_kind,enabled=true,alias_kind='canonical',updated_at=now();

insert into private.tenant_origin_aliases(tenant_id,app_kind,origin,alias_kind,metadata)
select tenant_id,'kds',private.normalize_https_origin(kds_origin),'canonical','{}'::jsonb
from private.tenant_runtime_config where enabled and private.normalize_https_origin(kds_origin) is not null
on conflict(origin) do update set tenant_id=excluded.tenant_id,app_kind=excluded.app_kind,enabled=true,alias_kind='canonical',updated_at=now();

-- Stable/current Git preview aliases used only for candidate certification.
insert into private.tenant_origin_aliases(tenant_id,app_kind,origin,alias_kind,metadata)
values
(private.reference_tenant_id(),'public','https://rohmat-pesan-bayar-publik-git-r-8bba8c-gramatikafoundation-3204.vercel.app','preview',jsonb_build_object('branch','release/master-clone-v1-freeze-20260919')),
(private.reference_tenant_id(),'public','https://rohmat-pesan-bayar-publik-gu51chc3b-gramatikafoundation-3204.vercel.app','preview',jsonb_build_object('deployment','dpl_D6VgcbCs8hqiZ8W9y6ArwSAam4oC')),
(private.reference_tenant_id(),'kds','https://rohmat-kds-printer-git-release-8ff48c-gramatikafoundation-3204.vercel.app','preview',jsonb_build_object('branch','release/master-clone-v1-freeze-20260919'))
on conflict(origin) do update
set tenant_id=excluded.tenant_id,app_kind=excluded.app_kind,enabled=true,alias_kind='preview',metadata=excluded.metadata,updated_at=now();

create or replace function public.master_prototype_resolve_origin(
  p_origin text,
  p_app_kind text default null
)
returns jsonb
language plpgsql
stable
security definer
set search_path=''
as $$
declare
  v_origin text;
  v private.tenant_origin_aliases%rowtype;
  c private.tenant_runtime_config%rowtype;
  t private.platform_tenants%rowtype;
begin
  v_origin:=private.normalize_https_origin(p_origin);
  if v_origin is null then
    return jsonb_build_object('ok',false,'error','invalid_origin');
  end if;
  if p_app_kind is not null and p_app_kind not in ('public','admin','kds') then
    return jsonb_build_object('ok',false,'error','invalid_app_kind');
  end if;

  select * into v
  from private.tenant_origin_aliases a
  where a.origin=v_origin
    and a.enabled
    and (p_app_kind is null or a.app_kind=p_app_kind)
  limit 1;

  if v.id is null then
    return jsonb_build_object('ok',false,'error','tenant_not_resolved');
  end if;

  select * into t from private.platform_tenants
   where id=v.tenant_id and status='active';
  select * into c from private.tenant_runtime_config
   where tenant_id=v.tenant_id and enabled;

  if t.id is null or c.tenant_id is null then
    return jsonb_build_object('ok',false,'error','tenant_unavailable');
  end if;

  return jsonb_build_object(
    'ok',true,
    'tenant_id',t.id,
    'tenant_slug',t.slug,
    'app_kind',v.app_kind,
    'business_name',c.business_name,
    'merchant_name',c.merchant_name,
    'locale',c.locale,
    'currency',c.currency,
    'timezone',c.timezone,
    'public_origin',private.normalize_https_origin(c.public_origin),
    'admin_origin',private.normalize_https_origin(c.admin_origin),
    'kds_origin',private.normalize_https_origin(c.kds_origin),
    'qris_asset',c.qris_asset,
    'storage_static_bucket',c.storage_static_bucket,
    'storage_payment_bucket',c.storage_payment_bucket,
    'table_count',c.table_count,
    'require_table_qr_signature',c.require_table_qr_signature,
    'resolved_origin',v.origin,
    'alias_kind',v.alias_kind
  );
end
$$;
revoke all on function public.master_prototype_resolve_origin(text,text) from public;
grant execute on function public.master_prototype_resolve_origin(text,text) to anon,authenticated,service_role;

comment on function public.master_prototype_resolve_origin(text,text) is
  'Non-secret fail-closed runtime tenant resolver. Resolves only pre-registered HTTPS origins; never falls back to the Rohmat reference tenant.';
