-- SMART ORDER B4: clone evidence + immutable master-promotion infrastructure.
-- This migration DOES NOT promote the prototype. Promotion is an explicit exact-head action.
begin;

create table if not exists private.master_clone_rehearsal_attestations (
  id bigint generated by default as identity primary key,
  contract text not null,
  source_commit_sha text not null check (source_commit_sha ~ '^[0-9a-f]{40}$'),
  rehearsal_blob_sha text not null check (rehearsal_blob_sha ~ '^[0-9a-f]{40}$'),
  result jsonb not null,
  verified_at timestamptz not null default now(),
  unique(source_commit_sha,contract)
);
alter table private.master_clone_rehearsal_attestations enable row level security;
revoke all on table private.master_clone_rehearsal_attestations from public,anon,authenticated;
grant select on table private.master_clone_rehearsal_attestations to service_role;

create table if not exists private.master_freeze_manifests (
  freeze_key text primary key,
  prototype_id uuid not null references private.platform_prototypes(id) on delete restrict,
  prototype_key text not null,
  release_tag text not null unique,
  source_repository text not null,
  source_commit_sha text not null check (source_commit_sha ~ '^[0-9a-f]{40}$'),
  source_branch text not null,
  runtime_deployment_id text not null check (runtime_deployment_id ~ '^dpl_[A-Za-z0-9]+$'),
  runtime_git_sha text not null check (runtime_git_sha ~ '^[0-9a-f]{40}$'),
  canonical_origin text not null,
  supabase_project_ref text not null,
  migration_head text not null check (migration_head ~ '^[0-9]{14}$'),
  schema_fingerprint text not null check (schema_fingerprint ~ '^[0-9a-f]{64}$'),
  cron_fingerprint text not null check (cron_fingerprint ~ '^[0-9a-f]{64}$'),
  manifest_fingerprint text not null check (manifest_fingerprint ~ '^[0-9a-f]{64}$'),
  clone_contract text not null,
  clone_rehearsal_blob_sha text not null check (clone_rehearsal_blob_sha ~ '^[0-9a-f]{40}$'),
  clone_ci_attestation text not null,
  frozen_at timestamptz not null default now(),
  metadata jsonb not null default '{}'::jsonb
);
alter table private.master_freeze_manifests enable row level security;
revoke all on table private.master_freeze_manifests from public,anon,authenticated;
grant select on table private.master_freeze_manifests to service_role;

create or replace function private.reject_immutable_master_evidence_mutation()
returns trigger
language plpgsql
security definer
set search_path=''
as $$
begin
  raise exception 'immutable_master_evidence';
end
$$;
revoke all on function private.reject_immutable_master_evidence_mutation() from public,anon,authenticated;

drop trigger if exists trg_master_clone_rehearsal_immutable on private.master_clone_rehearsal_attestations;
create trigger trg_master_clone_rehearsal_immutable
before update or delete on private.master_clone_rehearsal_attestations
for each row execute function private.reject_immutable_master_evidence_mutation();

drop trigger if exists trg_master_freeze_manifest_immutable on private.master_freeze_manifests;
create trigger trg_master_freeze_manifest_immutable
before update or delete on private.master_freeze_manifests
for each row execute function private.reject_immutable_master_evidence_mutation();

create or replace function private.guard_frozen_smart_order_prototype()
returns trigger
language plpgsql
security definer
set search_path=''
as $$
begin
  if old.prototype_key='smart-order-sdb-platform-v1'
     and old.status='active'
     and old.release_tag='smart-order-master-prototype-v1.0.0'
     and old.metadata->>'freeze_state'='frozen' then
    raise exception 'smart_order_master_v1_is_frozen';
  end if;
  return case when tg_op='DELETE' then old else new end;
end
$$;
revoke all on function private.guard_frozen_smart_order_prototype() from public,anon,authenticated;

drop trigger if exists zz_guard_frozen_smart_order_prototype on private.platform_prototypes;
create trigger zz_guard_frozen_smart_order_prototype
before update or delete on private.platform_prototypes
for each row execute function private.guard_frozen_smart_order_prototype();

create or replace function public.master_frozen_runtime_security_health_v1(p_tenant_id uuid)
returns jsonb
language plpgsql
stable
security definer
set search_path=''
as $$
declare
  v_base jsonb;
  c jsonb;
  v_frozen boolean;
  v_manifest boolean;
  v_ok boolean;
begin
  v_base:=public.master_runtime_security_health_v1(p_tenant_id);
  c:=coalesce(v_base->'checks','{}'::jsonb);

  select exists(
    select 1
    from private.platform_prototypes p
    where p.prototype_key='smart-order-sdb-platform-v1'
      and p.reference_tenant_id=p_tenant_id
      and p.status='active'
      and p.release_tag='smart-order-master-prototype-v1.0.0'
      and p.metadata->>'freeze_state'='frozen'
  ) into v_frozen;

  select exists(
    select 1
    from private.master_freeze_manifests m
    where m.prototype_key='smart-order-sdb-platform-v1'
      and m.release_tag='smart-order-master-prototype-v1.0.0'
      and m.prototype_id=(
        select p.id from private.platform_prototypes p
        where p.prototype_key='smart-order-sdb-platform-v1'
      )
  ) into v_manifest;

  v_ok :=
    coalesce((c->>'rls_off_tables')::integer,-1)=0
    and coalesce((c->>'anon_internal_rpc_execute')::integer,-1)=0
    and coalesce((c->>'client_rls_enforced')::boolean,false)
    and coalesce((c->>'single_canonical_origin')::boolean,false)
    and coalesce((c->>'canonical_aliases')::integer,-1)=1
    and coalesce((c->>'enabled_preview_aliases')::integer,-1)=0
    and coalesce((c->>'signed_table_qr_required')::boolean,false)
    and coalesce((c->>'valid_active_table_signatures')::integer,-1)
        = coalesce((c->>'table_count')::integer,-2)
    and coalesce((c->>'tenant_null_sessions')::integer,-1)=0
    and coalesce((c->>'active_kds_without_fingerprint')::integer,-1)=0
    and coalesce((c->>'post_cutover_admin_without_fingerprint')::integer,-1)=0
    and coalesce((c->>'post_cutover_sessions_over_6h')::integer,-1)=0
    and coalesce((c->>'four_surface_routes')::boolean,false)
    and v_frozen
    and v_manifest;

  return jsonb_build_object(
    'ok',v_ok,
    'contract','smart-order-master-frozen-runtime-security-v1',
    'tenant_id',p_tenant_id,
    'master_frozen',v_frozen,
    'immutable_manifest_present',v_manifest,
    'checks',c
  );
end
$$;
revoke all on function public.master_frozen_runtime_security_health_v1(uuid) from public,anon,authenticated;
grant execute on function public.master_frozen_runtime_security_health_v1(uuid) to service_role;

create or replace function private.promote_smart_order_master_v1(
  p_source_commit_sha text,
  p_runtime_deployment_id text,
  p_runtime_git_sha text,
  p_clone_rehearsal_blob_sha text,
  p_clone_ci_attestation text
)
returns jsonb
language plpgsql
security definer
set search_path=''
as $$
declare
  p private.platform_prototypes%rowtype;
  b private.release_baseline%rowtype;
  v_pre jsonb;
  v_candidate_security jsonb;
  v_frozen_security jsonb;
  v_engineering jsonb;
  v_att private.master_clone_rehearsal_attestations%rowtype;
  v_route text;
  v_ctx jsonb;
  v_now timestamptz:=clock_timestamp();
begin
  if p_source_commit_sha !~ '^[0-9a-f]{40}$'
     or p_runtime_git_sha !~ '^[0-9a-f]{40}$'
     or p_clone_rehearsal_blob_sha !~ '^[0-9a-f]{40}$'
     or p_runtime_deployment_id !~ '^dpl_[A-Za-z0-9]+$' then
    raise exception 'invalid_freeze_artifact_identity';
  end if;

  if p_clone_ci_attestation<>'github_actions_b4_clone_promotion_freeze_pass' then
    raise exception 'invalid_clone_ci_attestation';
  end if;

  select * into p
  from private.platform_prototypes
  where prototype_key='smart-order-sdb-platform-v1'
  for update;

  if p.id is null or p.status<>'draft' then
    raise exception 'master_candidate_not_draft';
  end if;
  if p.github_repo<>'gramatikafoundation-stack/smart-cassier'
     or p.supabase_project_ref<>'xrepmvbccalzhlcznrff'
     or p.tenancy_mode<>'shared_database_rls'
     or p.metadata->>'canonical_origin'<>'https://smart-order-sdb.vercel.app'
     or p.metadata->>'deployment_topology'<>'single_domain_four_surface'
     or p.metadata->>'b1_gate'<>'passed'
     or p.metadata->>'b2_gate'<>'passed'
     or p.metadata->>'b3_gate'<>'passed' then
    raise exception 'master_candidate_contract_mismatch';
  end if;

  select * into v_att
  from private.master_clone_rehearsal_attestations a
  where a.source_commit_sha=p_source_commit_sha
    and a.rehearsal_blob_sha=p_clone_rehearsal_blob_sha
    and a.contract='smart-order-b4-live-logical-clone-v2'
    and coalesce((a.result->>'ok')::boolean,false)
  order by a.verified_at desc
  limit 1;

  if v_att.id is null then
    raise exception 'exact_head_clone_attestation_missing';
  end if;

  v_pre:=private.release_preflight_status();
  if not coalesce((v_pre->>'ok')::boolean,false) then
    raise exception 'release_preflight_not_ready';
  end if;

  v_candidate_security:=public.master_runtime_security_health_v1(p.reference_tenant_id);
  if not coalesce((v_candidate_security->>'ok')::boolean,false) then
    raise exception 'candidate_runtime_security_not_ready';
  end if;

  foreach v_route in array array['public','admin','kds','database'] loop
    v_ctx:=public.master_prototype_resolve_origin('https://smart-order-sdb.vercel.app',v_route);
    if not coalesce((v_ctx->>'ok')::boolean,false)
       or (v_ctx->>'tenant_id')::uuid<>p.reference_tenant_id
       or v_ctx->>'surface_route'<>case v_route
          when 'public' then '/'
          when 'admin' then '/admin'
          when 'kds' then '/kds'
          when 'database' then '/database'
        end then
      raise exception 'canonical_four_surface_resolution_failed:%',v_route;
    end if;
  end loop;

  update private.release_policy
  set source_control_mode='git_tag_immutable_master_v1',
      ci_status='github_actions_b4_clone_promotion_freeze_pass',
      git_repo_connected=true,
      require_preflight=true,
      require_postflight=true,
      direct_production_changes_allowed=false,
      required_checks=jsonb_build_array(
        'migration_head','schema_fingerprint','cron_fingerprint','manifest_fingerprint',
        'rollback_refs','change_control','integration_contracts','tenant_isolation',
        'integrated_e2e','data_consistency','release_reliability','performance',
        'four_surface_network','ux','dr_restore_rehearsal','production_health',
        'clone_contract_v2','two_tenant_live_clone_rehearsal','exact_head_release_tag',
        'immutable_freeze_manifest','frozen_master_runtime_security'
      ),
      notes=coalesce(notes,'') || E'\n2026-09-27 B4 FINAL FREEZE: single-domain/four-surface clone v2 rehearsal passed on exact release source; immutable manifest + prototype guard enabled; candidate promoted only after genuine preflight.',
      updated_at=v_now
  where id=1;

  update private.platform_prototypes
  set status='active',
      release_tag='smart-order-master-prototype-v1.0.0',
      github_branch='release/smart-order-master-prototype-v1.0.0',
      metadata=coalesce(metadata,'{}'::jsonb) || jsonb_build_object(
        'freeze_state','frozen',
        'frozen_at',v_now,
        'master_contract','smart-order-master-prototype-v1',
        'clone_contract','smart-order-master-tenant-v2',
        'clone_rehearsal_contract','smart-order-b4-live-logical-clone-v2',
        'source_commit_sha',p_source_commit_sha,
        'release_tag','smart-order-master-prototype-v1.0.0',
        'runtime_deployment_id',p_runtime_deployment_id,
        'runtime_git_sha',p_runtime_git_sha,
        'clone_rehearsal_blob_sha',p_clone_rehearsal_blob_sha,
        'clone_ci_attestation',p_clone_ci_attestation,
        'immutable',true
      ),
      updated_at=v_now
  where id=p.id;

  insert into private.release_baseline(
    id,release_label,migration_head,schema_fingerprint,cron_fingerprint,
    manifest_fingerprint,captured_at,notes
  )
  values(
    1,
    'smart-order-master-prototype-v1.0.0',
    '20260927152500',
    private.release_schema_fingerprint(),
    private.release_cron_fingerprint(),
    private.release_manifest_fingerprint(),
    v_now,
    'SMART ORDER Master Prototype v1.0.0 immutable final freeze.'
  )
  on conflict(id) do update
  set release_label=excluded.release_label,
      migration_head=excluded.migration_head,
      schema_fingerprint=excluded.schema_fingerprint,
      cron_fingerprint=excluded.cron_fingerprint,
      manifest_fingerprint=excluded.manifest_fingerprint,
      captured_at=excluded.captured_at,
      notes=excluded.notes;

  select * into b from private.release_baseline where id=1;

  insert into private.master_freeze_manifests(
    freeze_key,prototype_id,prototype_key,release_tag,source_repository,
    source_commit_sha,source_branch,runtime_deployment_id,runtime_git_sha,
    canonical_origin,supabase_project_ref,migration_head,schema_fingerprint,
    cron_fingerprint,manifest_fingerprint,clone_contract,
    clone_rehearsal_blob_sha,clone_ci_attestation,frozen_at,metadata
  )
  values(
    'smart-order-master-prototype-v1.0.0',p.id,p.prototype_key,
    'smart-order-master-prototype-v1.0.0','gramatikafoundation-stack/smart-cassier',
    p_source_commit_sha,'release/smart-order-master-prototype-v1.0.0',
    p_runtime_deployment_id,p_runtime_git_sha,'https://smart-order-sdb.vercel.app',
    'xrepmvbccalzhlcznrff',b.migration_head,b.schema_fingerprint,b.cron_fingerprint,
    b.manifest_fingerprint,'smart-order-master-tenant-v2',p_clone_rehearsal_blob_sha,
    p_clone_ci_attestation,v_now,
    jsonb_build_object(
      'topology','single_domain_four_surface',
      'surface_routes',jsonb_build_object('public','/','admin','/admin','kds','/kds','database','/database'),
      'spreadsheet_provider','google_drive',
      'runtime_region','sin1',
      'rollback_deployment','dpl_4aReqWZcexyCzdCcgvcik4UmrfmZ'
    )
  );

  v_engineering:=private.release_engineering_status();
  v_frozen_security:=public.master_frozen_runtime_security_health_v1(p.reference_tenant_id);

  if not coalesce((v_engineering->>'ok')::boolean,false) then
    raise exception 'post_promotion_release_engineering_failed';
  end if;
  if not coalesce((v_frozen_security->>'ok')::boolean,false) then
    raise exception 'post_promotion_frozen_security_failed';
  end if;

  return jsonb_build_object(
    'ok',true,
    'contract','smart-order-master-promotion-v1',
    'release_tag','smart-order-master-prototype-v1.0.0',
    'source_commit_sha',p_source_commit_sha,
    'runtime_deployment_id',p_runtime_deployment_id,
    'runtime_git_sha',p_runtime_git_sha,
    'release_engineering',v_engineering,
    'frozen_runtime_security',v_frozen_security,
    'frozen_at',v_now
  );
end
$$;
revoke all on function private.promote_smart_order_master_v1(text,text,text,text,text) from public,anon,authenticated;

update private.release_policy
set source_control_mode='git_b4_clone_freeze_candidate',
    ci_status='b4_freeze_infrastructure_ready_promotion_pending',
    required_checks=jsonb_build_array(
      'migration_head','schema_fingerprint','cron_fingerprint','manifest_fingerprint',
      'rollback_refs','change_control','integration_contracts','tenant_isolation',
      'integrated_e2e','data_consistency','release_reliability','performance',
      'four_surface_network','ux','dr_restore_rehearsal','production_health',
      'clone_contract_v2','two_tenant_live_clone_rehearsal','promotion_pending'
    ),
    direct_production_changes_allowed=false,
    notes=coalesce(notes,'') || E'\nB4 freeze infrastructure installed. Promotion remains explicit and gated by exact-head live clone attestation.',
    updated_at=now()
where id=1;

insert into private.release_baseline(
  id,release_label,migration_head,schema_fingerprint,cron_fingerprint,
  manifest_fingerprint,captured_at,notes
)
values(
  1,
  'b4-clone-freeze-infrastructure-20260927',
  '20260927152500',
  private.release_schema_fingerprint(),
  private.release_cron_fingerprint(),
  private.release_manifest_fingerprint(),
  now(),
  'B4 clone/promotion/freeze infrastructure installed; master promotion pending.'
)
on conflict(id) do update
set release_label=excluded.release_label,
    migration_head=excluded.migration_head,
    schema_fingerprint=excluded.schema_fingerprint,
    cron_fingerprint=excluded.cron_fingerprint,
    manifest_fingerprint=excluded.manifest_fingerprint,
    captured_at=excluded.captured_at,
    notes=excluded.notes;

commit;
