-- ROHMAT MASTER PROTOTIPE v1
-- Phase 7: tenant-scoped design-system state and version history.
-- Global registries/theme profiles remain platform-wide; tenant design state is isolated.

create table if not exists private.tenant_design_system_versions (
  id bigint generated by default as identity primary key,
  tenant_id uuid not null references private.platform_tenants(id) on delete cascade,
  kind text not null check(kind in ('baseline','draft','published','rollback')),
  theme_id text not null default 'custom',
  theme_name text not null default 'Custom Theme',
  payload jsonb not null,
  created_by text,
  restored_from bigint,
  created_at timestamptz not null default now()
);
create index if not exists tenant_design_system_versions_tenant_created_idx
  on private.tenant_design_system_versions(tenant_id,created_at desc,id desc);
alter table private.tenant_design_system_versions enable row level security;
revoke all on private.tenant_design_system_versions from anon,authenticated;
drop policy if exists tenant_design_system_versions_service_role_all on private.tenant_design_system_versions;
create policy tenant_design_system_versions_service_role_all
on private.tenant_design_system_versions for all to service_role using(true) with check(true);

create or replace function private.tenant_design_system_state(p_tenant_id uuid)
returns jsonb
language sql
stable
security definer
set search_path=''
as $$
select coalesce(c.settings->'design_system','{}'::jsonb)
from private.tenant_runtime_config c
where c.tenant_id=p_tenant_id and c.enabled
limit 1
$$;
revoke all on function private.tenant_design_system_state(uuid) from public,anon,authenticated;
grant execute on function private.tenant_design_system_state(uuid) to service_role;

create or replace function private.tenant_design_system_apply_payload(
  p_tenant_id uuid,p_actor text,p_payload jsonb,p_kind text,p_restored_from bigint default null
)
returns jsonb
language plpgsql
security definer
set search_path=''
as $$
declare
  v_id bigint;
  v_theme jsonb;
  v_state jsonb;
  v_payload jsonb;
begin
  if p_payload is null or jsonb_typeof(p_payload)<>'object' then
    return jsonb_build_object('ok',false,'error','invalid_payload');
  end if;
  if p_kind not in ('published','rollback') then
    return jsonb_build_object('ok',false,'error','invalid_kind');
  end if;
  if not exists(select 1 from private.tenant_runtime_config where tenant_id=p_tenant_id and enabled) then
    return jsonb_build_object('ok',false,'error','tenant_unavailable');
  end if;

  v_payload:=p_payload||jsonb_build_object(
    'status','published','publishedAt',now(),'publishedBy',coalesce(p_actor,'admin')
  );
  v_theme:=coalesce(v_payload->'theme','{}'::jsonb);

  insert into private.tenant_design_system_versions(
    tenant_id,kind,theme_id,theme_name,payload,created_by,restored_from
  ) values(
    p_tenant_id,p_kind,left(coalesce(v_theme->>'id','custom'),100),
    left(coalesce(v_theme->>'name','Custom Theme'),160),
    v_payload,left(coalesce(p_actor,'admin'),200),p_restored_from
  ) returning id into v_id;

  v_state:=coalesce(private.tenant_design_system_state(p_tenant_id),'{}'::jsonb);
  v_state:=v_state||jsonb_build_object(
    'version',3,
    'published',v_payload,
    'publishedVersionId',v_id,
    'updatedAt',now()
  );

  update private.tenant_runtime_config
     set settings=jsonb_set(coalesce(settings,'{}'::jsonb),'{design_system}',v_state,true),
         updated_at=now()
   where tenant_id=p_tenant_id and enabled;

  perform private.sync_tenant_public_settings_projection(p_tenant_id);
  return jsonb_build_object('ok',true,'tenant_id',p_tenant_id,'versionId',v_id,'designSystem',v_state);
end
$$;
revoke all on function private.tenant_design_system_apply_payload(uuid,text,jsonb,text,bigint) from public,anon,authenticated;
grant execute on function private.tenant_design_system_apply_payload(uuid,text,jsonb,text,bigint) to service_role;

create or replace function public.admin_design_system_history_tenant(p_tenant_id uuid,p_token text)
returns jsonb
language plpgsql
security definer
set search_path=''
as $$
declare v_email extensions.citext; v_rows jsonb;
begin
  v_email:=private.tenant_admin_email_from_token(p_tenant_id,p_token);
  if v_email is null then return jsonb_build_object('ok',false,'error','invalid_session'); end if;
  select coalesce(jsonb_agg(jsonb_build_object(
    'id',id,'kind',kind,'themeId',theme_id,'themeName',theme_name,
    'createdAt',created_at,'createdBy',created_by,'restoredFrom',restored_from
  ) order by id desc),'[]'::jsonb)
  into v_rows
  from (
    select * from private.tenant_design_system_versions
    where tenant_id=p_tenant_id order by id desc limit 50
  ) h;
  return jsonb_build_object('ok',true,'tenant_id',p_tenant_id,'versions',v_rows);
end
$$;
revoke all on function public.admin_design_system_history_tenant(uuid,text) from public,anon,authenticated;
grant execute on function public.admin_design_system_history_tenant(uuid,text) to service_role;

create or replace function public.admin_design_system_save_draft_tenant(
  p_tenant_id uuid,p_token text,p_payload jsonb
)
returns jsonb
language plpgsql
security definer
set search_path=''
as $$
declare v_email extensions.citext; v_id bigint; v_theme jsonb; v_state jsonb; v_draft jsonb;
begin
  v_email:=private.tenant_admin_email_from_token(p_tenant_id,p_token);
  if v_email is null then return jsonb_build_object('ok',false,'error','invalid_session'); end if;
  if p_payload is null or jsonb_typeof(p_payload)<>'object' then
    return jsonb_build_object('ok',false,'error','invalid_payload');
  end if;
  v_theme:=coalesce(p_payload->'theme','{}'::jsonb);
  v_draft:=p_payload||jsonb_build_object(
    'status','draft','draftUpdatedAt',now(),'draftUpdatedBy',v_email::text
  );
  insert into private.tenant_design_system_versions(
    tenant_id,kind,theme_id,theme_name,payload,created_by
  ) values(
    p_tenant_id,'draft',left(coalesce(v_theme->>'id','custom'),100),
    left(coalesce(v_theme->>'name','Custom Theme'),160),v_draft,v_email::text
  ) returning id into v_id;
  v_draft:=v_draft||jsonb_build_object('draftVersionId',v_id);
  v_state:=coalesce(private.tenant_design_system_state(p_tenant_id),'{}'::jsonb)
    ||jsonb_build_object('version',3,'draft',v_draft,'updatedAt',now());
  update private.tenant_runtime_config
     set settings=jsonb_set(coalesce(settings,'{}'::jsonb),'{design_system}',v_state,true),
         updated_at=now()
   where tenant_id=p_tenant_id and enabled;
  return jsonb_build_object('ok',true,'tenant_id',p_tenant_id,'versionId',v_id,'designSystem',v_state);
end
$$;
revoke all on function public.admin_design_system_save_draft_tenant(uuid,text,jsonb) from public,anon,authenticated;
grant execute on function public.admin_design_system_save_draft_tenant(uuid,text,jsonb) to service_role;

create or replace function public.admin_design_system_publish_tenant(
  p_tenant_id uuid,p_token text,p_payload jsonb
)
returns jsonb
language plpgsql
security definer
set search_path=''
as $$
declare v_email extensions.citext;
begin
  v_email:=private.tenant_admin_email_from_token(p_tenant_id,p_token);
  if v_email is null then return jsonb_build_object('ok',false,'error','invalid_session'); end if;
  return private.tenant_design_system_apply_payload(p_tenant_id,v_email::text,p_payload,'published',null);
end
$$;
revoke all on function public.admin_design_system_publish_tenant(uuid,text,jsonb) from public,anon,authenticated;
grant execute on function public.admin_design_system_publish_tenant(uuid,text,jsonb) to service_role;

create or replace function public.admin_design_system_rollback_tenant(
  p_tenant_id uuid,p_token text,p_version_id bigint
)
returns jsonb
language plpgsql
security definer
set search_path=''
as $$
declare v_email extensions.citext; v_payload jsonb;
begin
  v_email:=private.tenant_admin_email_from_token(p_tenant_id,p_token);
  if v_email is null then return jsonb_build_object('ok',false,'error','invalid_session'); end if;
  select payload into v_payload
    from private.tenant_design_system_versions
   where tenant_id=p_tenant_id and id=p_version_id and kind in ('baseline','published','rollback');
  if v_payload is null then return jsonb_build_object('ok',false,'error','version_not_found'); end if;
  return private.tenant_design_system_apply_payload(p_tenant_id,v_email::text,v_payload,'rollback',p_version_id);
end
$$;
revoke all on function public.admin_design_system_rollback_tenant(uuid,text,bigint) from public,anon,authenticated;
grant execute on function public.admin_design_system_rollback_tenant(uuid,text,bigint) to service_role;

create or replace function public.admin_design_system_registry_tenant(
  p_tenant_id uuid,p_token text,p_site text,p_page text
)
returns jsonb
language plpgsql
security definer
set search_path=''
as $$
declare v_email extensions.citext; v_rows jsonb;
begin
  v_email:=private.tenant_admin_email_from_token(p_tenant_id,p_token);
  if v_email is null then return jsonb_build_object('ok',false,'error','invalid_session'); end if;
  if p_site not in ('public','admin','kds','database') then
    return jsonb_build_object('ok',false,'error','site_invalid');
  end if;
  select coalesce(jsonb_agg(jsonb_build_object(
    'id',r.element_id,'label',r.label,'sort',r.sort_order
  ) order by r.sort_order,r.label),'[]'::jsonb)
  into v_rows
  from public.design_element_registry r
  where r.site=p_site and r.page=p_page;
  return jsonb_build_object('ok',true,'tenant_id',p_tenant_id,'elements',v_rows);
end
$$;
revoke all on function public.admin_design_system_registry_tenant(uuid,text,text,text) from public,anon,authenticated;
grant execute on function public.admin_design_system_registry_tenant(uuid,text,text,text) to service_role;

create or replace function public.admin_theme_profile_catalog_tenant(p_tenant_id uuid,p_token text)
returns jsonb
language plpgsql
security definer
set search_path=''
as $$
declare v_email extensions.citext; v_result jsonb;
begin
  v_email:=private.tenant_admin_email_from_token(p_tenant_id,p_token);
  if v_email is null then return jsonb_build_object('ok',false,'error','invalid_session'); end if;
  select coalesce(jsonb_agg(profile order by name),'[]'::jsonb)
    into v_result from private.theme_profiles;
  return jsonb_build_object('ok',true,'tenant_id',p_tenant_id,'profiles',v_result);
end
$$;
revoke all on function public.admin_theme_profile_catalog_tenant(uuid,text) from public,anon,authenticated;
grant execute on function public.admin_theme_profile_catalog_tenant(uuid,text) to service_role;

create or replace function private.tenant_design_base(p_tenant_id uuid,p_publish boolean)
returns jsonb
language sql
stable
security definer
set search_path=''
as $$
select case
  when coalesce(p_publish,false) then coalesce(private.tenant_design_system_state(p_tenant_id)->'published','{}'::jsonb)
  else case
    when jsonb_typeof(private.tenant_design_system_state(p_tenant_id)->'draft')='object'
      and coalesce(private.tenant_design_system_state(p_tenant_id)->'draft','{}'::jsonb)<>'{}'::jsonb
      then private.tenant_design_system_state(p_tenant_id)->'draft'
    else coalesce(private.tenant_design_system_state(p_tenant_id)->'published','{}'::jsonb)
  end
end
$$;
revoke all on function private.tenant_design_base(uuid,boolean) from public,anon,authenticated;
grant execute on function private.tenant_design_base(uuid,boolean) to service_role;

create or replace function public.admin_design_system_set_element_tenant(
  p_tenant_id uuid,p_token text,p_site text,p_page text,p_element text,p_config jsonb,p_publish boolean default false
)
returns jsonb
language plpgsql
security definer
set search_path=''
as $$
declare
  v_email extensions.citext;
  v_base jsonb;
  v_clean jsonb;
  v_path text[];
  v_existing jsonb;
  v_merged jsonb;
begin
  v_email:=private.tenant_admin_email_from_token(p_tenant_id,p_token);
  if v_email is null then return jsonb_build_object('ok',false,'error','invalid_session'); end if;
  if not exists(select 1 from public.design_element_registry r
    where r.site=p_site and r.page=p_page and r.element_id=p_element) then
    return jsonb_build_object('ok',false,'error','element_not_allowed');
  end if;
  v_clean:=private.design_sanitize_element_config(p_config);
  if v_clean='{}'::jsonb then return jsonb_build_object('ok',false,'error','empty_or_invalid_config'); end if;

  v_base:=private.tenant_design_base(p_tenant_id,p_publish);
  v_base:=jsonb_set(v_base,'{elements}',coalesce(v_base->'elements','{}'::jsonb),true);
  v_base:=jsonb_set(v_base,array['elements',p_site],coalesce(v_base#>array['elements',p_site],'{}'::jsonb),true);
  v_base:=jsonb_set(v_base,array['elements',p_site,p_page],coalesce(v_base#>array['elements',p_site,p_page],'{}'::jsonb),true);
  v_path:=array['elements',p_site,p_page,p_element];
  v_existing:=coalesce(v_base#>v_path,'{}'::jsonb);
  v_merged:=v_existing;
  if v_clean?'content' then v_merged:=jsonb_set(v_merged,'{content}',coalesce(v_merged->'content','{}'::jsonb)||(v_clean->'content'),true); end if;
  if v_clean?'typography' then v_merged:=jsonb_set(v_merged,'{typography}',coalesce(v_merged->'typography','{}'::jsonb)||(v_clean->'typography'),true); end if;
  if v_clean?'colors' then v_merged:=jsonb_set(v_merged,'{colors}',coalesce(v_merged->'colors','{}'::jsonb)||(v_clean->'colors'),true); end if;
  if v_clean?'layout' then v_merged:=jsonb_set(v_merged,'{layout}',coalesce(v_merged->'layout','{}'::jsonb)||(v_clean->'layout'),true); end if;
  v_base:=jsonb_set(v_base,v_path,v_merged,true);

  if coalesce(p_publish,false) then
    return private.tenant_design_system_apply_payload(p_tenant_id,v_email::text,v_base,'published',null);
  end if;
  return public.admin_design_system_save_draft_tenant(p_tenant_id,p_token,v_base);
end
$$;
revoke all on function public.admin_design_system_set_element_tenant(uuid,text,text,text,text,jsonb,boolean) from public,anon,authenticated;
grant execute on function public.admin_design_system_set_element_tenant(uuid,text,text,text,text,jsonb,boolean) to service_role;

create or replace function public.admin_design_system_reset_element_tenant(
  p_tenant_id uuid,p_token text,p_site text,p_page text,p_element text,p_publish boolean default false
)
returns jsonb
language plpgsql
security definer
set search_path=''
as $$
declare v_email extensions.citext; v_base jsonb; v_path text[];
begin
  v_email:=private.tenant_admin_email_from_token(p_tenant_id,p_token);
  if v_email is null then return jsonb_build_object('ok',false,'error','invalid_session'); end if;
  if not exists(select 1 from public.design_element_registry r
    where r.site=p_site and r.page=p_page and r.element_id=p_element) then
    return jsonb_build_object('ok',false,'error','element_not_allowed');
  end if;
  v_base:=private.tenant_design_base(p_tenant_id,p_publish);
  v_path:=array['elements',p_site,p_page,p_element];
  v_base:=v_base#-v_path;
  if coalesce(p_publish,false) then
    return private.tenant_design_system_apply_payload(p_tenant_id,v_email::text,v_base,'published',null);
  end if;
  return public.admin_design_system_save_draft_tenant(p_tenant_id,p_token,v_base);
end
$$;
revoke all on function public.admin_design_system_reset_element_tenant(uuid,text,text,text,text,boolean) from public,anon,authenticated;
grant execute on function public.admin_design_system_reset_element_tenant(uuid,text,text,text,text,boolean) to service_role;

create or replace function private.tenant_design_scope_clean(p_config jsonb)
returns jsonb
language plpgsql
immutable
set search_path=''
as $$
declare
  v_typ jsonb:='{}'::jsonb;
  v_col jsonb:='{}'::jsonb;
  v_clean jsonb:='{}'::jsonb;
  v_key text;
  v_value text;
  v_num numeric;
begin
  p_config:=coalesce(p_config,'{}'::jsonb);
  v_value:=p_config#>>'{typography,family}';
  if v_value in ('system-ui','Inter','Manrope','Segoe UI','Arial','Helvetica','Calibri','Georgia','Times New Roman','Garamond','Palatino Linotype','Courier New') then
    v_typ:=v_typ||jsonb_build_object('family',v_value);
  end if;
  if (p_config#>>'{typography,size}')~'^-?[0-9]+([.][0-9]+)?$' then
    v_num:=greatest(10,least(72,(p_config#>>'{typography,size}')::numeric));
    v_typ:=v_typ||jsonb_build_object('size',v_num);
  end if;
  if (p_config#>>'{typography,weight}')~'^[0-9]+$' then
    v_num:=greatest(300,least(900,(p_config#>>'{typography,weight}')::numeric));
    v_typ:=v_typ||jsonb_build_object('weight',v_num);
  end if;
  if p_config#>'{typography,italic}' is not null then
    v_typ:=v_typ||jsonb_build_object('italic',coalesce((p_config#>>'{typography,italic}')::boolean,false));
  end if;
  v_value:=p_config#>>'{typography,align}';
  if v_value in ('left','center','right','justify') then v_typ:=v_typ||jsonb_build_object('align',v_value); end if;
  if (p_config#>>'{typography,lineHeight}')~'^-?[0-9]+([.][0-9]+)?$' then
    v_num:=greatest(1,least(2,(p_config#>>'{typography,lineHeight}')::numeric));
    v_typ:=v_typ||jsonb_build_object('lineHeight',v_num);
  end if;
  if (p_config#>>'{typography,letterSpacing}')~'^-?[0-9]+([.][0-9]+)?$' then
    v_num:=greatest(-2,least(6,(p_config#>>'{typography,letterSpacing}')::numeric));
    v_typ:=v_typ||jsonb_build_object('letterSpacing',v_num);
  end if;
  foreach v_key in array array['text','background','primary','accent','panel','muted'] loop
    v_value:=p_config#>>array['colors',v_key];
    if v_value~*'^#[0-9a-f]{6}$' then v_col:=v_col||jsonb_build_object(v_key,upper(v_value)); end if;
  end loop;
  if v_typ<>'{}'::jsonb then v_clean:=v_clean||jsonb_build_object('typography',v_typ); end if;
  if v_col<>'{}'::jsonb then v_clean:=v_clean||jsonb_build_object('colors',v_col); end if;
  return v_clean;
end
$$;

create or replace function public.admin_design_system_set_scope_tenant(
  p_tenant_id uuid,p_token text,p_scope text,p_site text,p_page text,p_config jsonb,p_publish boolean default false
)
returns jsonb
language plpgsql
security definer
set search_path=''
as $$
declare
  v_email extensions.citext; v_base jsonb; v_target jsonb; v_clean jsonb; v_path text[];
begin
  v_email:=private.tenant_admin_email_from_token(p_tenant_id,p_token);
  if v_email is null then return jsonb_build_object('ok',false,'error','invalid_session'); end if;
  if p_scope not in ('site','page') or p_site not in ('public','admin','kds','database') then
    return jsonb_build_object('ok',false,'error','invalid_scope');
  end if;
  if p_scope='page' and coalesce(p_page,'')!~'^[a-z0-9][a-z0-9-]{0,63}$' then
    return jsonb_build_object('ok',false,'error','invalid_page');
  end if;
  v_clean:=private.tenant_design_scope_clean(p_config);
  if v_clean='{}'::jsonb then return jsonb_build_object('ok',false,'error','empty_config'); end if;

  v_base:=private.tenant_design_base(p_tenant_id,p_publish);
  if p_scope='site' then
    v_base:=jsonb_set(v_base,'{sites}',coalesce(v_base->'sites','{}'::jsonb),true);
    v_path:=array['sites',p_site];
  else
    v_base:=jsonb_set(v_base,'{pages}',coalesce(v_base->'pages','{}'::jsonb),true);
    v_base:=jsonb_set(v_base,array['pages',p_site],coalesce(v_base#>array['pages',p_site],'{}'::jsonb),true);
    v_path:=array['pages',p_site,p_page];
  end if;
  v_target:=coalesce(v_base#>v_path,'{}'::jsonb);
  if v_clean?'typography' then
    v_target:=jsonb_set(v_target,'{typography}',coalesce(v_target->'typography','{}'::jsonb)||(v_clean->'typography'),true);
  end if;
  if v_clean?'colors' then
    v_target:=jsonb_set(v_target,'{colors}',coalesce(v_target->'colors','{}'::jsonb)||(v_clean->'colors'),true);
  end if;
  v_base:=jsonb_set(v_base,v_path,v_target,true);

  if coalesce(p_publish,false) then
    return private.tenant_design_system_apply_payload(p_tenant_id,v_email::text,v_base,'published',null);
  end if;
  return public.admin_design_system_save_draft_tenant(p_tenant_id,p_token,v_base);
end
$$;
revoke all on function public.admin_design_system_set_scope_tenant(uuid,text,text,text,text,jsonb,boolean) from public,anon,authenticated;
grant execute on function public.admin_design_system_set_scope_tenant(uuid,text,text,text,text,jsonb,boolean) to service_role;

create or replace function public.admin_design_system_reset_scope_tenant(
  p_tenant_id uuid,p_token text,p_scope text,p_site text,p_page text,p_publish boolean default true
)
returns jsonb
language plpgsql
security definer
set search_path=''
as $$
declare v_email extensions.citext; v_base jsonb; v_target jsonb; v_path text[];
begin
  v_email:=private.tenant_admin_email_from_token(p_tenant_id,p_token);
  if v_email is null then return jsonb_build_object('ok',false,'error','invalid_session'); end if;
  if p_scope not in ('site','page') or p_site not in ('public','admin','kds','database') then
    return jsonb_build_object('ok',false,'error','invalid_scope');
  end if;
  if p_scope='page' and coalesce(p_page,'')!~'^[a-z0-9][a-z0-9-]{0,63}$' then
    return jsonb_build_object('ok',false,'error','invalid_page');
  end if;
  v_base:=private.tenant_design_base(p_tenant_id,p_publish);
  if p_scope='site' then
    v_base:=jsonb_set(v_base,'{sites}',coalesce(v_base->'sites','{}'::jsonb),true);
    v_path:=array['sites',p_site];
  else
    v_base:=jsonb_set(v_base,'{pages}',coalesce(v_base->'pages','{}'::jsonb),true);
    v_base:=jsonb_set(v_base,array['pages',p_site],coalesce(v_base#>array['pages',p_site],'{}'::jsonb),true);
    v_path:=array['pages',p_site,p_page];
  end if;
  v_target:=coalesce(v_base#>v_path,'{}'::jsonb)-'typography'-'colors';
  v_base:=jsonb_set(v_base,v_path,v_target,true);
  if coalesce(p_publish,false) then
    return private.tenant_design_system_apply_payload(p_tenant_id,v_email::text,v_base,'published',null);
  end if;
  return public.admin_design_system_save_draft_tenant(p_tenant_id,p_token,v_base);
end
$$;
revoke all on function public.admin_design_system_reset_scope_tenant(uuid,text,text,text,text,boolean) from public,anon,authenticated;
grant execute on function public.admin_design_system_reset_scope_tenant(uuid,text,text,text,text,boolean) to service_role;

do $$
declare
  v_tenant uuid:=private.reference_tenant_id();
  v_state jsonb;
begin
  v_state:=coalesce((select design_system from public.site_settings where id=1),'{}'::jsonb);
  update private.tenant_runtime_config
     set settings=jsonb_set(coalesce(settings,'{}'::jsonb),'{design_system}',v_state,true),
         updated_at=now()
   where tenant_id=v_tenant
     and coalesce(settings->'design_system','{}'::jsonb)='{}'::jsonb;
  perform private.sync_tenant_public_settings_projection(v_tenant);
  if not exists(select 1 from private.tenant_design_system_versions where tenant_id=v_tenant) then
    insert into private.tenant_design_system_versions(tenant_id,kind,theme_id,theme_name,payload,created_by)
    values(
      v_tenant,'baseline',
      coalesce(v_state#>>'{published,theme,id}','rohmat-reference'),
      coalesce(v_state#>>'{published,theme,name}','Rohmat Reference'),
      coalesce(v_state->'published',v_state,'{}'::jsonb),
      'migration'
    );
  end if;
end
$$;
