-- Generated from validated SDB AI control-plane; contains NO secrets.\ninsert into sdb_ai.products(product_key,display_name,enabled,risk_profile,data_policy) values ('sdb-core','SDB AI Core','t','high','{"allow_secrets": false, "allow_full_table_dump": false, "allow_raw_payment_credentials": false}'::jsonb) on conflict(product_key) do update set display_name=excluded.display_name,enabled=excluded.enabled,risk_profile=excluded.risk_profile,data_policy=excluded.data_policy,updated_at=now();
insert into sdb_ai.products(product_key,display_name,enabled,risk_profile,data_policy) values ('smart-cashier','SMART CASHIER','t','high','{"allow_secrets": false, "allow_full_table_dump": false, "allow_raw_payment_credentials": false}'::jsonb) on conflict(product_key) do update set display_name=excluded.display_name,enabled=excluded.enabled,risk_profile=excluded.risk_profile,data_policy=excluded.data_policy,updated_at=now();
insert into sdb_ai.products(product_key,display_name,enabled,risk_profile,data_policy) values ('smart-insight','SMART INSIGHT','t','medium','{"allow_secrets": false, "allow_full_table_dump": false, "allow_raw_payment_credentials": false}'::jsonb) on conflict(product_key) do update set display_name=excluded.display_name,enabled=excluded.enabled,risk_profile=excluded.risk_profile,data_policy=excluded.data_policy,updated_at=now();
insert into sdb_ai.products(product_key,display_name,enabled,risk_profile,data_policy) values ('smart-asisten','SMART ASISTEN','t','high','{"allow_secrets": false, "allow_full_table_dump": false, "allow_raw_payment_credentials": false}'::jsonb) on conflict(product_key) do update set display_name=excluded.display_name,enabled=excluded.enabled,risk_profile=excluded.risk_profile,data_policy=excluded.data_policy,updated_at=now();
insert into sdb_ai.products(product_key,display_name,enabled,risk_profile,data_policy) values ('media-ai','Media AI','t','medium','{"allow_secrets": false, "allow_full_table_dump": false, "allow_raw_payment_credentials": false}'::jsonb) on conflict(product_key) do update set display_name=excluded.display_name,enabled=excluded.enabled,risk_profile=excluded.risk_profile,data_policy=excluded.data_policy,updated_at=now();

insert into sdb_ai.model_routes(task_class,primary_model,fallback_model,reasoning_effort,max_output_tokens,max_input_bytes,enabled) values ('simple','gpt-5.6-luna','gpt-5.6-sol','low',1200,32768,'t') on conflict(task_class) do update set primary_model=excluded.primary_model,fallback_model=excluded.fallback_model,reasoning_effort=excluded.reasoning_effort,max_output_tokens=excluded.max_output_tokens,max_input_bytes=excluded.max_input_bytes,enabled=excluded.enabled,updated_at=now();
insert into sdb_ai.model_routes(task_class,primary_model,fallback_model,reasoning_effort,max_output_tokens,max_input_bytes,enabled) values ('standard','gpt-5.6-luna','gpt-5.6-sol','medium',2400,65536,'t') on conflict(task_class) do update set primary_model=excluded.primary_model,fallback_model=excluded.fallback_model,reasoning_effort=excluded.reasoning_effort,max_output_tokens=excluded.max_output_tokens,max_input_bytes=excluded.max_input_bytes,enabled=excluded.enabled,updated_at=now();
insert into sdb_ai.model_routes(task_class,primary_model,fallback_model,reasoning_effort,max_output_tokens,max_input_bytes,enabled) values ('complex','gpt-5.6-sol','gpt-5.6-luna','high',5000,131072,'t') on conflict(task_class) do update set primary_model=excluded.primary_model,fallback_model=excluded.fallback_model,reasoning_effort=excluded.reasoning_effort,max_output_tokens=excluded.max_output_tokens,max_input_bytes=excluded.max_input_bytes,enabled=excluded.enabled,updated_at=now();
insert into sdb_ai.model_routes(task_class,primary_model,fallback_model,reasoning_effort,max_output_tokens,max_input_bytes,enabled) values ('vision','gpt-5.6-luna','gpt-5.6-sol','medium',2400,1048576,'t') on conflict(task_class) do update set primary_model=excluded.primary_model,fallback_model=excluded.fallback_model,reasoning_effort=excluded.reasoning_effort,max_output_tokens=excluded.max_output_tokens,max_input_bytes=excluded.max_input_bytes,enabled=excluded.enabled,updated_at=now();

insert into sdb_ai.model_rates(model,input_usd_per_million,output_usd_per_million,source_note) values ('gpt-5.6-luna',0.200000,1.200000,'OpenAI models page, checked 2026-09-30') on conflict(model) do update set input_usd_per_million=excluded.input_usd_per_million,output_usd_per_million=excluded.output_usd_per_million,source_note=excluded.source_note,updated_at=now();
insert into sdb_ai.model_rates(model,input_usd_per_million,output_usd_per_million,source_note) values ('gpt-5.6-sol',4.000000,20.000000,'OpenAI models page, checked 2026-09-30') on conflict(model) do update set input_usd_per_million=excluded.input_usd_per_million,output_usd_per_million=excluded.output_usd_per_million,source_note=excluded.source_note,updated_at=now();

insert into sdb_ai.prompt_registry(product_key,prompt_key,task_class,instructions,response_schema,active,version) values ('smart-cashier','business.insight','standard','Anda adalah analis bisnis SMART CASHIER. Gunakan hanya data terstruktur yang diberikan. Jangan mengarang angka. Pisahkan fakta terukur dari interpretasi. Prioritaskan temuan yang dapat ditindaklanjuti, sebutkan keterbatasan data, dan jangan mengambil tindakan finansial.','{"type": "object", "required": ["summary", "key_findings", "recommended_actions", "risks_or_limits", "confidence"], "properties": {"summary": {"type": "string"}, "confidence": {"type": "number", "maximum": 1, "minimum": 0}, "key_findings": {"type": "array", "items": {"type": "string"}}, "risks_or_limits": {"type": "array", "items": {"type": "string"}}, "recommended_actions": {"type": "array", "items": {"type": "string"}}}, "additionalProperties": false}'::jsonb,'t',1) on conflict(product_key,prompt_key,version) do update set task_class=excluded.task_class,instructions=excluded.instructions,response_schema=excluded.response_schema,active=excluded.active,updated_at=now();
insert into sdb_ai.prompt_registry(product_key,prompt_key,task_class,instructions,response_schema,active,version) values ('smart-insight','survey.insight','standard','Anda adalah analis SMART INSIGHT. Gunakan hanya data survei yang diberikan. Jangan mengarang statistik. Bedakan temuan kuantitatif, tema kualitatif, dan keterbatasan sampel. Jangan mengidentifikasi responden.','{"type": "object", "required": ["summary", "themes", "notable_patterns", "limitations", "recommended_actions", "confidence"], "properties": {"themes": {"type": "array", "items": {"type": "string"}}, "summary": {"type": "string"}, "confidence": {"type": "number", "maximum": 1, "minimum": 0}, "limitations": {"type": "array", "items": {"type": "string"}}, "notable_patterns": {"type": "array", "items": {"type": "string"}}, "recommended_actions": {"type": "array", "items": {"type": "string"}}}, "additionalProperties": false}'::jsonb,'t',1) on conflict(product_key,prompt_key,version) do update set task_class=excluded.task_class,instructions=excluded.instructions,response_schema=excluded.response_schema,active=excluded.active,updated_at=now();
insert into sdb_ai.prompt_registry(product_key,prompt_key,task_class,instructions,response_schema,active,version) values ('smart-asisten','reasoning.advice','complex','Anda adalah reasoning layer untuk SMART ASISTEN. Berikan rencana dan analisis; jangan mengklaim tindakan telah dilakukan. Tandai tindakan yang perlu approval. Utamakan jalur native/API yang paling aman dan efisien.','{"type": "object", "required": ["summary", "plan", "risks", "needs_approval", "confidence"], "properties": {"plan": {"type": "array", "items": {"type": "string"}}, "risks": {"type": "array", "items": {"type": "string"}}, "summary": {"type": "string"}, "confidence": {"type": "number", "maximum": 1, "minimum": 0}, "needs_approval": {"type": "array", "items": {"type": "string"}}}, "additionalProperties": false}'::jsonb,'t',1) on conflict(product_key,prompt_key,version) do update set task_class=excluded.task_class,instructions=excluded.instructions,response_schema=excluded.response_schema,active=excluded.active,updated_at=now();
insert into sdb_ai.prompt_registry(product_key,prompt_key,task_class,instructions,response_schema,active,version) values ('media-ai','editorial.assist','standard','Anda adalah asisten redaksi. Jangan menciptakan fakta, kutipan, nama, tanggal, atau sumber. Pisahkan fakta yang diberikan dari klaim yang masih perlu verifikasi. Jaga netralitas dan bahasa layak tayang.','{"type": "object", "required": ["summary", "key_facts", "verification_needed", "possible_angles", "cautions"], "properties": {"summary": {"type": "string"}, "cautions": {"type": "array", "items": {"type": "string"}}, "key_facts": {"type": "array", "items": {"type": "string"}}, "possible_angles": {"type": "array", "items": {"type": "string"}}, "verification_needed": {"type": "array", "items": {"type": "string"}}}, "additionalProperties": false}'::jsonb,'t',1) on conflict(product_key,prompt_key,version) do update set task_class=excluded.task_class,instructions=excluded.instructions,response_schema=excluded.response_schema,active=excluded.active,updated_at=now();
insert into sdb_ai.prompt_registry(product_key,prompt_key,task_class,instructions,response_schema,active,version) values ('sdb-core','business.advisor','complex','Anda adalah analis strategi internal Smart Digital For Business. Gunakan hanya konteks bisnis yang diberikan. Prioritaskan efektivitas, efisiensi, keamanan, ROI, dan langkah yang dapat diverifikasi. Jangan membuat keputusan keuangan final atas nama manusia.','{"type": "object", "required": ["summary", "opportunities", "recommendations", "risks", "next_steps", "confidence"], "properties": {"risks": {"type": "array", "items": {"type": "string"}}, "summary": {"type": "string"}, "confidence": {"type": "number", "maximum": 1, "minimum": 0}, "next_steps": {"type": "array", "items": {"type": "string"}}, "opportunities": {"type": "array", "items": {"type": "string"}}, "recommendations": {"type": "array", "items": {"type": "string"}}}, "additionalProperties": false}'::jsonb,'t',1) on conflict(product_key,prompt_key,version) do update set task_class=excluded.task_class,instructions=excluded.instructions,response_schema=excluded.response_schema,active=excluded.active,updated_at=now();

insert into sdb_ai.tool_policies(product_key,tool_name,risk_level,requires_approval,allowed_roles,active) values ('smart-cashier','read_business_metrics','read','f','{owner,admin,viewer}'::text[],'t') on conflict(product_key,tool_name) do update set risk_level=excluded.risk_level,requires_approval=excluded.requires_approval,allowed_roles=excluded.allowed_roles,active=excluded.active,updated_at=now();
insert into sdb_ai.tool_policies(product_key,tool_name,risk_level,requires_approval,allowed_roles,active) values ('smart-cashier','recommend_action','read','f','{owner,admin}'::text[],'t') on conflict(product_key,tool_name) do update set risk_level=excluded.risk_level,requires_approval=excluded.requires_approval,allowed_roles=excluded.allowed_roles,active=excluded.active,updated_at=now();
insert into sdb_ai.tool_policies(product_key,tool_name,risk_level,requires_approval,allowed_roles,active) values ('smart-cashier','change_transaction','critical','t','{owner}'::text[],'t') on conflict(product_key,tool_name) do update set risk_level=excluded.risk_level,requires_approval=excluded.requires_approval,allowed_roles=excluded.allowed_roles,active=excluded.active,updated_at=now();
insert into sdb_ai.tool_policies(product_key,tool_name,risk_level,requires_approval,allowed_roles,active) values ('smart-cashier','refund_payment','critical','t','{owner}'::text[],'t') on conflict(product_key,tool_name) do update set risk_level=excluded.risk_level,requires_approval=excluded.requires_approval,allowed_roles=excluded.allowed_roles,active=excluded.active,updated_at=now();
insert into sdb_ai.tool_policies(product_key,tool_name,risk_level,requires_approval,allowed_roles,active) values ('smart-insight','read_survey_aggregate','read','f','{analyst,owner,admin}'::text[],'t') on conflict(product_key,tool_name) do update set risk_level=excluded.risk_level,requires_approval=excluded.requires_approval,allowed_roles=excluded.allowed_roles,active=excluded.active,updated_at=now();
insert into sdb_ai.tool_policies(product_key,tool_name,risk_level,requires_approval,allowed_roles,active) values ('smart-asisten','propose_plan','read','f','{owner,admin}'::text[],'t') on conflict(product_key,tool_name) do update set risk_level=excluded.risk_level,requires_approval=excluded.requires_approval,allowed_roles=excluded.allowed_roles,active=excluded.active,updated_at=now();
insert into sdb_ai.tool_policies(product_key,tool_name,risk_level,requires_approval,allowed_roles,active) values ('smart-asisten','execute_external_action','external_action','t','{owner}'::text[],'t') on conflict(product_key,tool_name) do update set risk_level=excluded.risk_level,requires_approval=excluded.requires_approval,allowed_roles=excluded.allowed_roles,active=excluded.active,updated_at=now();
insert into sdb_ai.tool_policies(product_key,tool_name,risk_level,requires_approval,allowed_roles,active) values ('media-ai','draft_from_verified_facts','read','f','{editor,owner,admin}'::text[],'t') on conflict(product_key,tool_name) do update set risk_level=excluded.risk_level,requires_approval=excluded.requires_approval,allowed_roles=excluded.allowed_roles,active=excluded.active,updated_at=now();
insert into sdb_ai.tool_policies(product_key,tool_name,risk_level,requires_approval,allowed_roles,active) values ('media-ai','publish_content','external_action','t','{editor,owner}'::text[],'t') on conflict(product_key,tool_name) do update set risk_level=excluded.risk_level,requires_approval=excluded.requires_approval,allowed_roles=excluded.allowed_roles,active=excluded.active,updated_at=now();
insert into sdb_ai.tool_policies(product_key,tool_name,risk_level,requires_approval,allowed_roles,active) values ('sdb-core','read_business_summary','read','f','{owner,admin}'::text[],'t') on conflict(product_key,tool_name) do update set risk_level=excluded.risk_level,requires_approval=excluded.requires_approval,allowed_roles=excluded.allowed_roles,active=excluded.active,updated_at=now();
insert into sdb_ai.tool_policies(product_key,tool_name,risk_level,requires_approval,allowed_roles,active) values ('sdb-core','approve_spend','critical','t','{owner}'::text[],'t') on conflict(product_key,tool_name) do update set risk_level=excluded.risk_level,requires_approval=excluded.requires_approval,allowed_roles=excluded.allowed_roles,active=excluded.active,updated_at=now();

insert into sdb_ai.spend_controls(product_key,requests_per_minute,daily_request_limit,monthly_input_token_limit,monthly_output_token_limit,enabled) values ('smart-cashier',30,1000,10000000,2000000,'t') on conflict(product_key) do update set requests_per_minute=excluded.requests_per_minute,daily_request_limit=excluded.daily_request_limit,monthly_input_token_limit=excluded.monthly_input_token_limit,monthly_output_token_limit=excluded.monthly_output_token_limit,enabled=excluded.enabled,updated_at=now();
insert into sdb_ai.spend_controls(product_key,requests_per_minute,daily_request_limit,monthly_input_token_limit,monthly_output_token_limit,enabled) values ('smart-insight',20,300,10000000,2000000,'t') on conflict(product_key) do update set requests_per_minute=excluded.requests_per_minute,daily_request_limit=excluded.daily_request_limit,monthly_input_token_limit=excluded.monthly_input_token_limit,monthly_output_token_limit=excluded.monthly_output_token_limit,enabled=excluded.enabled,updated_at=now();
insert into sdb_ai.spend_controls(product_key,requests_per_minute,daily_request_limit,monthly_input_token_limit,monthly_output_token_limit,enabled) values ('smart-asisten',20,500,8000000,2000000,'t') on conflict(product_key) do update set requests_per_minute=excluded.requests_per_minute,daily_request_limit=excluded.daily_request_limit,monthly_input_token_limit=excluded.monthly_input_token_limit,monthly_output_token_limit=excluded.monthly_output_token_limit,enabled=excluded.enabled,updated_at=now();
insert into sdb_ai.spend_controls(product_key,requests_per_minute,daily_request_limit,monthly_input_token_limit,monthly_output_token_limit,enabled) values ('media-ai',30,800,10000000,2500000,'t') on conflict(product_key) do update set requests_per_minute=excluded.requests_per_minute,daily_request_limit=excluded.daily_request_limit,monthly_input_token_limit=excluded.monthly_input_token_limit,monthly_output_token_limit=excluded.monthly_output_token_limit,enabled=excluded.enabled,updated_at=now();
insert into sdb_ai.spend_controls(product_key,requests_per_minute,daily_request_limit,monthly_input_token_limit,monthly_output_token_limit,enabled) values ('sdb-core',10,200,5000000,1500000,'t') on conflict(product_key) do update set requests_per_minute=excluded.requests_per_minute,daily_request_limit=excluded.daily_request_limit,monthly_input_token_limit=excluded.monthly_input_token_limit,monthly_output_token_limit=excluded.monthly_output_token_limit,enabled=excluded.enabled,updated_at=now();\n