import "jsr:@supabase/functions-js/edge-runtime.d.ts";
const U=Deno.env.get("SUPABASE_URL")||"",K=Deno.env.get("SUPABASE_PUBLISHABLE_KEY")||Deno.env.get("SUPABASE_ANON_KEY")||"",BACKUP="public:admin-kds-ui-v5-perf-backup";
let memo:Promise<string>|null=null;
async function payload(){if(!U||!K)throw Error("tenant_config_missing");if(memo)return memo;memo=(async()=>{const r=await fetch(U+"/rest/v1/runtime_asset_backups?select=content&name=eq."+encodeURIComponent(BACKUP)+"&limit=1",{headers:{apikey:K,Authorization:"Bearer "+K},cache:"no-store"});if(!r.ok)throw Error("backup_unavailable");const a=await r.json(),c=a?.[0]?.content;if(typeof c!=="string"||c.length<1000)throw Error("backup_missing");return c.split("localStorage").join("sessionStorage")})();return memo}
const PATCH=String.raw`(()=>{'use strict';
if(window.__rohmatKdsUiV9)return;window.__rohmatKdsUiV9=1;
function tx(x){return String(x||'').replace(/\s+/g,' ').trim()}
function ctx(){return{main:tx(document.querySelector('.mainNav button.on')?.textContent).toUpperCase(),sub:tx(document.querySelector('.subnav button.on')?.textContent)}}
function css(){if(document.getElementById('rohmatKdsUiV9Css'))return;const s=document.createElement('style');s.id='rohmatKdsUiV9Css';s.textContent='html[data-rohmat-kds-three-status="1"] #view{display:none!important}';document.head.appendChild(s)}
function apply(){css();const c=ctx(),on=c.main==='KDS'&&c.sub==='Pesanan';if(on)document.documentElement.dataset.rohmatKdsThreeStatus='1';else delete document.documentElement.dataset.rohmatKdsThreeStatus}
document.addEventListener('rohmat:navigation',()=>setTimeout(apply,40));document.addEventListener('click',e=>{if(e.target.closest('.mainNav button,.subnav button'))setTimeout(apply,60)},true);window.addEventListener('pageshow',apply);new MutationObserver(apply).observe(document.body,{childList:true,subtree:false});apply();
})();`;
Deno.serve(async(req:Request)=>{if(req.method!=="GET"&&req.method!=="HEAD")return new Response("Method Not Allowed",{status:405});const et='"rohmat-admin-kdsui-v10"',im=req.headers.get('if-none-match')||'';if(im.includes('rohmat-admin-kdsui-v10'))return new Response(null,{status:304,headers:{etag:et,"cache-control":"no-cache, max-age=0, must-revalidate"}});try{const js=(await payload())+"\n"+PATCH;return new Response(req.method==="HEAD"?null:js,{status:200,headers:{"content-type":"application/javascript; charset=utf-8","cache-control":"no-cache, max-age=0, must-revalidate",etag:et,"access-control-allow-origin":"*","cross-origin-resource-policy":"cross-origin","x-content-type-options":"nosniff","x-rohmat-admin-kds-ui":"v10-session-coherent-three-status"}})}catch{return new Response("/* unavailable */",{status:503,headers:{"content-type":"application/javascript; charset=utf-8","cache-control":"no-store"}})}});