import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2.57.4";
const U=Deno.env.get('SUPABASE_URL')||'';
const S=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||'';
const K=Deno.env.get('SUPABASE_PUBLISHABLE_KEY')||Deno.env.get('SUPABASE_ANON_KEY')||'';
const UUID_RE=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const JS=String.raw`(()=>{'use strict';
if(window.__rohmatDbRealtimeV13)return;window.__rohmatDbRealtimeV13=1;
const API='__SUPABASE_URL__/functions/v1/rohmat-admin-order-history-v1',RT_KEY='__PUBLISHABLE_KEY__';
const TENANT='__SDB_TENANT_ID__',SHEET='__SPREADSHEET_URL__';
let rows=[],busy=false,lastSig='',lastLoad=0,sheetHealth=null,total=0;
let rtSocket=null,rtConnected=false,rtRef=0,rtHeartbeat=null,rtReconnect=null,historyPollTimer=null;
const LOCALE='__TENANT_LOCALE__',CURRENCY='__TENANT_CURRENCY__',TIMEZONE='__TENANT_TIMEZONE__';const tx=s=>String(s||'').replace(/\s+/g,' ').trim(),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),rp=n=>new Intl.NumberFormat(LOCALE,{style:'currency',currency:CURRENCY,maximumFractionDigits:0}).format(Number(n)||0);
const source=s=>s==='cashier_admin'?'Smart Cashier Admin':s==='cashier_kds'?'Smart Cashier KDS':s==='public'?'Situs Publik / Barcode':(s||'—');
const service=s=>s==='dine-in'?'Dine In':s==='take-away'?'Take Away':(s||'—');
const pay=s=>s==='cash'?'Cash':s==='qris_cashier'?'QRIS Kasir':s==='qris'?'QRIS':(s||'—');
const ord=s=>({confirmed:'Pesanan Baru',preparing:'Sedang Diproses',ready:'Siap',completed:'Pesanan Selesai',payment_review:'Menunggu Verifikasi'}[s]||s||'—');
function isDb(){return tx(document.querySelector('.mainNav button.on')?.textContent).toUpperCase()==='DATABASE'}function isHistory(){const s=tx(document.querySelector('.subnav button.on')?.textContent);return isDb()&&(s==='Riwayat Pesanan'||s==='Riwayat')}
function token(){let v=localStorage.getItem('rohmat-admin-session-v4')||sessionStorage.getItem('rohmat-admin-session-v4')||'';if(v&&v[0]==='{'){try{const j=JSON.parse(v);v=j.token||j.access_token||''}catch{}}return String(v||'')}
async function api(body){const t=token();if(!t)throw Error('Sesi Admin tidak ditemukan.');const res=await fetch(API+'?t='+Date.now(),{method:'POST',cache:'no-store',headers:{'content-type':'application/json','x-admin-session':t,'x-sdb-tenant-id':TENANT},body:JSON.stringify(body||{})});const j=await res.json().catch(()=>({}));if(!res.ok||!j.ok)throw Error(j.error||'Layanan Admin gagal');return j}
function rtUrl(){if(!RT_KEY)return'';const u=new URL('__SUPABASE_URL__');u.protocol=u.protocol==='https:'?'wss:':'ws:';u.pathname='/realtime/v1/websocket';u.search='?apikey='+encodeURIComponent(RT_KEY)+'&vsn=1.0.0';return u.toString()}
function rtSend(topic,event,payload,joinRef=null){if(!rtSocket||rtSocket.readyState!==WebSocket.OPEN)return'';rtRef+=1;rtSocket.send(JSON.stringify({topic,event,payload,ref:String(rtRef),join_ref:joinRef}));return String(rtRef)}
function stopRt(){rtConnected=false;if(rtHeartbeat){clearInterval(rtHeartbeat);rtHeartbeat=null}if(rtReconnect){clearTimeout(rtReconnect);rtReconnect=null}if(rtSocket){try{rtSocket.onopen=rtSocket.onmessage=rtSocket.onerror=rtSocket.onclose=null;rtSocket.close()}catch{}rtSocket=null}}
function scheduleRt(ms=1500){if(document.hidden||!navigator.onLine||!token())return;if(rtReconnect)clearTimeout(rtReconnect);rtReconnect=setTimeout(()=>{rtReconnect=null;startRt().catch(()=>scheduleRt(Math.min(30000,ms*2)))},ms)}
function scheduleHistoryPoll(){if(historyPollTimer)clearTimeout(historyPollTimer);historyPollTimer=setTimeout(async()=>{if(!document.hidden&&isHistory())await load(false);scheduleHistoryPoll()},rtConnected?45000:5000)}
async function startRt(){if(rtConnected||document.hidden||!navigator.onLine||!token())return;const url=rtUrl();if(!url)return;stopRt();const ticket=await api({action:'realtime'}),rt=ticket.realtime||{},topic=String(rt.topic||''),eventName=String(rt.event||'kds_change');if(!topic.startsWith('kds:'))throw Error('realtime_ticket_invalid');const ws=new WebSocket(url);rtSocket=ws;await new Promise((resolve,reject)=>{let settled=false,joinRef='';const timeout=setTimeout(()=>{if(!settled){settled=true;reject(Error('realtime_join_timeout'))}},8000);ws.onopen=()=>{joinRef=rtSend('realtime:'+topic,'phx_join',{config:{broadcast:{ack:false,self:false},presence:{key:''},postgres_changes:[],private:false},access_token:RT_KEY},'1')};ws.onmessage=e=>{let m;try{m=JSON.parse(String(e.data))}catch{return}if(m.event==='phx_reply'&&String(m.ref||'')===String(joinRef)){if(m.payload?.status!=='ok'){if(!settled){settled=true;clearTimeout(timeout);reject(Error('realtime_join_rejected'))}return}if(!settled){settled=true;clearTimeout(timeout);rtConnected=true;rtHeartbeat=setInterval(()=>rtSend('phoenix','heartbeat',{},null),25000);scheduleHistoryPoll();resolve()}}if(m.event==='broadcast'&&m.payload?.event===eventName){const detail=m.payload?.payload||{};document.dispatchEvent(new CustomEvent('rohmat:orders-changed',{detail}));if(isHistory())load(true)}};ws.onerror=()=>{if(!settled){settled=true;clearTimeout(timeout);reject(Error('realtime_socket_error'))}};ws.onclose=()=>{rtConnected=false;scheduleHistoryPoll();scheduleRt()}})}
function dt(v,t){if(!v)return'—';try{return t==='d'?new Date(v).toLocaleDateString(LOCALE,{timeZone:TIMEZONE,day:'2-digit',month:'2-digit',year:'numeric'}):new Date(v).toLocaleTimeString(LOCALE,{timeZone:TIMEZONE,hour:'2-digit',minute:'2-digit',second:'2-digit'})+' WIB'}catch{return'—'}}
function items(o){return(Array.isArray(o?.items)?o.items:[]).map(i=>({name:String(i?.name??i?.menu_name??'Menu'),qty:Math.max(1,Number(i?.quantity??i?.qty??1)||1),price:Math.max(0,Number(i?.price??i?.unit_price??0)||0)}))}
function openSheet(){const w=window.open(SHEET,'_blank','noopener,noreferrer');if(!w)location.href=SHEET}
function css(){if(document.getElementById('rohmatDbRtCss13'))return;const s=document.createElement('style');s.id='rohmatDbRtCss13';s.textContent='#rohmatDbSafe9{display:block!important;width:100%}.rd13h{display:flex;justify-content:space-between;align-items:center;gap:12px;flex-wrap:wrap;margin:4px 0 12px}.rd13status{display:flex;gap:7px;align-items:center;flex-wrap:wrap}.rd13chip{font-size:11px;font-weight:850;padding:6px 9px;border:1px solid var(--line);border-radius:999px;background:var(--panel2)}.rd13ok{color:#2f6f56}.rd13wait{color:#9a6a22}.rd13wrap{overflow:auto;border:1px solid var(--line);border-radius:15px;background:var(--panel);max-height:calc(100vh - 250px)}.rd13tbl{width:100%;min-width:1900px;border-collapse:collapse}.rd13tbl th,.rd13tbl td{padding:9px 10px;border-bottom:1px solid var(--line);text-align:left;vertical-align:top;font-size:11px}.rd13tbl th{background:var(--panel2);position:sticky;top:0;z-index:2;white-space:nowrap}.rd13items{display:grid;gap:2px;min-width:190px}.rd13total{font-weight:900;white-space:nowrap}.rd13empty,.rd13err{padding:24px;text-align:center}.rd13err{color:#9a4238;background:#fff0ed;border-radius:12px}.rd13btn{display:inline-flex;border:0;border-radius:10px;padding:9px 12px;background:var(--primary);color:#fff;text-decoration:none;font-weight:850;cursor:pointer}';document.head.appendChild(s)}
function root(){const v=document.getElementById('view');if(!v)return null;let r=document.getElementById('rohmatDbSafe9');if(!r){r=document.createElement('section');r.id='rohmatDbSafe9'}if(r.parentElement!==v||v.children.length!==1||v.firstElementChild!==r)v.replaceChildren(r);return r}
function nav(){const n=document.querySelector('.subnav');if(!n)return;n.removeAttribute('data-rd13')}
function syncText(){const h=sheetHealth||{},c=h.consistency||{},pending=Number(h.pending||0),processing=Number(h.processing||0),failed=Number(h.failed||0),dead=Number(h.dead||0),queue=pending+processing+failed+dead,targets=Number(c.targets||h.active_targets||0),consistent=Number(c.consistent_targets||0),inconsistent=Number(c.inconsistent_targets||0),lastSync=h.last_synced_at?new Date(h.last_synced_at):null,lastEvent=h.last_event_at?new Date(h.last_event_at):null,lastCheck=c.last_checked_at?new Date(c.last_checked_at):null,covered=!lastEvent||(lastSync&&lastSync>=lastEvent),checked=!lastEvent||(lastCheck&&lastCheck>=lastEvent),targetsOk=targets>0&&c.ok===true&&consistent===targets&&inconsistent===0,healthy=h.enabled===true&&h.writer_configured===true&&queue===0&&targetsOk&&covered&&checked,fmt=d=>d&&!Number.isNaN(d.getTime())?d.toLocaleTimeString(LOCALE,{timeZone:TIMEZONE,hour:'2-digit',minute:'2-digit',second:'2-digit'}):'—',title='writer='+(h.writer_configured===true?'aktif':'tidak siap')+'; target='+consistent+'/'+targets+'; pending='+pending+'; processing='+processing+'; failed='+failed+'; dead='+dead+'; last_sync='+fmt(lastSync)+'; last_check='+fmt(lastCheck);if(healthy)return'<span class="rd13chip rd13ok" title="'+esc(title)+'">Sheet sinkron tervalidasi · '+fmt(lastSync)+' · '+consistent+'/'+targets+'</span>';if(h.enabled!==true||h.writer_configured!==true)return'<span class="rd13chip rd13wait" title="'+esc(title)+'">Sheet: writer tidak siap</span>';if(queue>0)return'<span class="rd13chip rd13wait" title="'+esc(title)+'">Sheet menunggu · '+queue+' antrean/error</span>';if(!targetsOk)return'<span class="rd13chip rd13wait" title="'+esc(title)+'">Sheet belum konsisten · '+consistent+'/'+targets+'</span>';if(!covered||!checked)return'<span class="rd13chip rd13wait" title="'+esc(title)+'">Sheet perlu verifikasi event terbaru</span>';return'<span class="rd13chip rd13wait" title="'+esc(title)+'">Sheet: status belum tervalidasi</span>'}
function render(){if(!isHistory())return;css();const r=root();if(!r)return;const body=rows.length?rows.map(o=>{const a=items(o),it=a.length?'<div class="rd13items">'+a.map(i=>'<span><b>'+i.qty+'×</b> '+esc(i.name)+' · '+rp(i.price)+'</span>').join('')+'</div>':'—';return'<tr><td><b>'+esc(o.public_order_code||'—')+'</b></td><td>'+dt(o.created_at,'d')+'</td><td>'+dt(o.created_at,'t')+'</td><td>'+esc(source(o.order_source))+'</td><td>'+esc(service(o.service_mode))+'</td><td>'+esc(o.service_mode==='dine-in'?(o.table_number||'—'):'—')+'</td><td>'+esc(o.customer_name||'—')+'</td><td>'+esc(o.customer_whatsapp||'—')+'</td><td>'+it+'</td><td>'+Number(o.item_count||0)+'</td><td class="rd13total">'+rp(o.total_amount||0)+'</td><td>'+esc(pay(o.payment_method))+'</td><td>'+esc(o.payment_status||'—')+'</td><td>'+esc(ord(o.order_status))+'</td><td>'+dt(o.payment_submitted_at||o.verified_at||o.kitchen_sent_at||o.created_at,'t')+'</td><td>'+dt(o.preparing_at||o.ready_at,'t')+'</td><td>'+dt(o.completed_at,'t')+'</td><td>'+esc(o.customer_note||'—')+'</td><td>'+esc(o.cashier_actor||'—')+'</td></tr>'}).join(''):'<tr><td colspan="19" class="rd13empty">Belum ada riwayat pesanan.</td></tr>';r.innerHTML='<div class="rd13h"><div class="rd13status"><span class="rd13chip rd13ok">Database live · '+total+' transaksi</span>'+syncText()+'</div><button class="rd13btn" type="button" id="rd13OpenSheet">Spreadsheet ↗</button></div><div class="rd13wrap"><table class="rd13tbl"><thead><tr><th>Kode Pesanan</th><th>Tanggal</th><th>Waktu</th><th>Sumber</th><th>Layanan</th><th>Meja</th><th>Pemesan</th><th>No. WA</th><th>Menu, Jumlah & Harga</th><th>Item</th><th>Total</th><th>Metode Bayar</th><th>Status Bayar</th><th>Status Pesanan</th><th>Pesanan Baru</th><th>Diproses</th><th>Selesai</th><th>Catatan</th><th>Petugas Kasir</th></tr></thead><tbody>'+body+'</tbody></table></div>';document.getElementById('rd13OpenSheet')?.addEventListener('click',openSheet)}
async function load(force=false){if(!isHistory()||busy||document.hidden)return;if(!force&&Date.now()-lastLoad<900)return;const t=token();if(!t){const r=root();if(r)r.innerHTML='<div class="rd13err">Sesi Admin tidak ditemukan. Silakan login kembali.</div>';return}busy=true;lastLoad=Date.now();try{const j=await api({action:'snapshot',limit:1000,offset:0});const next=Array.isArray(j.rows)?j.rows:[],sig=JSON.stringify(next.map(x=>[x.id,x.updated_at,x.order_status,x.payment_status,x.total_amount,x.items]));sheetHealth=j.sheet_sync||null;total=Number(j.total||next.length);if(force||sig!==lastSig){rows=next;lastSig=sig;render()}else{const st=document.querySelector('.rd13status');if(st)st.innerHTML='<span class="rd13chip rd13ok">Database live · '+total+' transaksi</span>'+syncText()}}catch(e){const r=root();if(r)r.innerHTML='<div class="rd13err"><b>Riwayat Pesanan gagal dimuat.</b><br>'+esc(e.message||e)+'</div>'}finally{busy=false}}
function activate(){nav();if(!isHistory()){document.getElementById('rohmatDbSafe9')?.remove();return}render();load(true)}
document.addEventListener('click',e=>{if(e.target.closest('.mainNav button,.subnav button'))setTimeout(activate,50)},true);document.addEventListener('rohmat:navigation',()=>{setTimeout(activate,40);startRt().catch(()=>scheduleRt())});document.addEventListener('rohmat:cashier-order-created',()=>setTimeout(()=>load(true),50));document.addEventListener('visibilitychange',()=>{if(document.hidden){stopRt();if(historyPollTimer){clearTimeout(historyPollTimer);historyPollTimer=null}}else{setTimeout(()=>load(true),50);startRt().catch(()=>scheduleRt());scheduleHistoryPoll()}});window.addEventListener('online',()=>startRt().catch(()=>scheduleRt()));window.addEventListener('offline',()=>stopRt());window.addEventListener('focus',()=>{setTimeout(()=>load(true),50);startRt().catch(()=>scheduleRt())});window.addEventListener('pageshow',()=>{setTimeout(activate,80);startRt().catch(()=>scheduleRt())});scheduleHistoryPoll();if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{setTimeout(activate,100);startRt().catch(()=>scheduleRt())},{once:true});else{setTimeout(activate,100);startRt().catch(()=>scheduleRt())};
})();`;
Deno.serve(async(req:Request)=>{
  if(req.method!=='GET'&&req.method!=='HEAD')return new Response('Method Not Allowed',{status:405});
  if(!U||!S)return new Response('/* platform configuration incomplete */',{status:503,headers:{'content-type':'application/javascript; charset=utf-8','cache-control':'no-store'}});
  const u=new URL(req.url),tenantId=String(u.searchParams.get('tenant')||req.headers.get('x-sdb-tenant-id')||'').trim();
  if(!UUID_RE.test(tenantId))return new Response('/* tenant required */',{status:400,headers:{'content-type':'application/javascript; charset=utf-8','cache-control':'no-store'}});
  const sb=createClient(U,S,{auth:{persistSession:false,autoRefreshToken:false}});
  const [ctx,cfg]=await Promise.all([
    sb.rpc('master_prototype_tenant_context',{p_tenant_id:tenantId}),
    sb.rpc('tenant_sheet_sync_config',{p_tenant_id:tenantId})
  ]);
  if(ctx.error||!ctx.data?.ok||ctx.data?.enabled===false||cfg.error||!cfg.data?.ok){
    return new Response('/* tenant unavailable */',{status:404,headers:{'content-type':'application/javascript; charset=utf-8','cache-control':'no-store'}});
  }
  const targets=Array.isArray(cfg.data.targets)?cfg.data.targets:[];
  const target=targets.find((x:any)=>x.enabled!==false)||targets[0]||null;
  const sheet=target?.spreadsheet_id?'https://docs.google.com/spreadsheets/d/'+target.spreadsheet_id+'/edit':'';
  const body=JS
    .replaceAll('__SUPABASE_URL__',U.replace(/\/$/,''))
    .replaceAll('__PUBLISHABLE_KEY__',K)
    .replaceAll('__SDB_TENANT_ID__',tenantId)
    .replaceAll('__SPREADSHEET_URL__',sheet)
    .replaceAll('__TENANT_LOCALE__',String(ctx.data.locale||'id-ID'))
    .replaceAll('__TENANT_CURRENCY__',String(ctx.data.currency||'IDR'))
    .replaceAll('__TENANT_TIMEZONE__',String(ctx.data.timezone||'Asia/Jakarta'));
  return new Response(req.method==='HEAD'?null:body,{status:200,headers:{
    'content-type':'application/javascript; charset=utf-8',
    'cache-control':'no-cache, max-age=0, must-revalidate',
    'etag':'"rohmat-admin-dbui-master-prototype-v1-'+tenantId.slice(0,8)+'"',
    'access-control-allow-origin':'*',
    'cross-origin-resource-policy':'cross-origin',
    'x-content-type-options':'nosniff',
    'vary':'X-SDB-Tenant-ID',
    'x-sdb-tenant-id':tenantId,
    'x-rohmat-admin-db-ui':'master-prototype-v1'
  }});
});